//! src/TA-Lib.h generation
//!
//! Each TA-Lib function is defined in 'src/ta-lib/include/ta_func.h'
//! on the following form:
//!
//! ```c
//! TA_LIB_API TA_RetCode TA_ACCBANDS(
//!    int startIdx,
//!    int endIdx,
//!    const double inHigh[],
//!    const double inLow[],
//!    const double inClose[],
//!    int optInTimePeriod, /* From 2 to 100000 */
//!    int *outBegIdx,
//!    int *outNBElement,
//!    double outRealUpperBand[],
//!    double outRealMiddleBand[],
//!    double outRealLowerBand[]
//! );
//! ```
//!
//! so every prototype can be mined directly and rewritten as one
//! variadic X-macro line per indicator (plus one for its
//! TA_<NAME>_Lookback() companion). The hand-written src/init.c
//! #includes the generated header several times, expanding those
//! lines via the macro helpers of src/wrapper.h into wrapper
//! definitions and the .Call() registration table, keeping the C
//! binding logic in exactly one place.

/// One TA-Lib function mined from ta_func.h, reduced to what the
/// X-macro lines need
#[allow(non_camel_case_types)]
#[derive(Debug, Default, PartialEq)]
pub struct TA_Lib {
    pub indicator: String,
    pub argument_type: &'static str,
    pub input: Vec<String>,
    pub optional_input: Vec<String>,
    pub output_indicators: Vec<String>,
    pub output_names: Vec<String>,
}

/// The full src/TA-Lib.h: one TA_INDICATOR line per function,
/// then one TA_LOOKBACK line per function
pub fn render_header(names: &[String], header: &str) -> String {
    let header = purge_comments(header);
    let funcs: Vec<TA_Lib> = names
        .iter()
        .map(|n| extract_signature(n, &header))
        .collect();

    let mut out = String::from(concat!(
        "// TA-Lib.h - Autogenerated via codegen/\n",
        "// Description:\n",
        "//\n",
        "// \t\tTA_INDICATOR: TA-Lib indicator.\n",
        "// \t\tTA_INPUT: Indicator input.\n",
        "// \t\tTA_OPTIONS: Indicator input.\n",
        "// \t\tTA_OUTPUT: Indicator input.\n",
        "// \t\tTA_OUTPUT_NAMES: Indicator input.\n",
        "// \t\tTA_LOOKBACK: Indicator lookback (name + optional inputs).\n",
        "//\n",
        "// clang-format off\n",
    ));

    for f in &funcs {
        out.push_str(&indicator_macro(f));
        out.push('\n');
    }

    out.push('\n');
    out.push_str("// Lookback\n");
    for f in &funcs {
        out.push_str(&lookback_macro(f));
        out.push('\n');
    }

    out.push_str("// clang-format on\n");
    out
}

/// TA_INDICATOR: The indicator function of TA-Lib, e.g. TA_SMA() and its type
/// TA_INPUT: The input to the TA-Lib indicator, e.g. inReal
/// TA_OPTIONS: The optional input in the TA-Lib indicator, e.g. optInWindow
/// TA_OUTPUT: The output from the TA-Lib indicator, e.g. outReal
/// TA_OUTPUT_NAME: The output names from the TA-Lib indicator, e.g. outReal, outRealMiddleBand etc.
fn indicator_macro(function: &TA_Lib) -> String {
    format!(
        "TA_INDICATOR({}, {}, TA_INPUT({}), TA_OPTIONS({}), TA_OUTPUT({}), TA_OUTPUT_NAME({}), {})",
        function.indicator,
        function.argument_type,
        function.input.join(", "),
        function.optional_input.join(", "),
        function.output_indicators.join(", "),
        function.output_names.join(", "),
        if function.indicator.starts_with("CDL") {
            "CANDLESTICK"
        } else {
            "NOT_CANDLESTICK"
        }
    )
}

/// The TA_<indicator>_Lookback() companion of each indicator takes
/// exactly the indicator's optional inputs, so its macro only needs
/// the name and TA_OPTIONS. Void lookbacks (e.g. TA_ACOS_Lookback)
/// yield an empty TA_OPTIONS()
fn lookback_macro(function: &TA_Lib) -> String {
    format!(
        "TA_LOOKBACK({}, TA_OPTIONS({}))",
        function.indicator,
        function.optional_input.join(", "),
    )
}

/// Drop every '/* ... */' block comment (each replaced by a single
/// space) so prototype mining never matches commented-out code
fn purge_comments(header: &str) -> String {
    let mut out = String::with_capacity(header.len());
    let mut rest = header;

    while let Some(start) = rest.find("/*") {
        out.push_str(&rest[..start]);
        out.push(' ');
        rest = match rest[start + 2..].find("*/") {
            Some(end) => &rest[start + 2 + end + 2..],
            None => "",
        };
    }

    out.push_str(rest);
    out
}

/// The identifier of a parameter: drop `[]`/`*` and take the last token.
fn parameter_identifier(param: &str) -> String {
    param
        .replace("[]", " ")
        .replace('*', " ")
        .split_whitespace()
        .last()
        .unwrap_or("")
        .to_string()
}

/// Mine the TA_<indicator>() prototype from the (comment-purged)
/// header; panics if the prototype is not found
fn extract_signature(indicator: &str, header: &str) -> TA_Lib {
    let needle = format!("TA_RetCode TA_{indicator}(");

    let start = header
        .find(&needle)
        .unwrap_or_else(|| panic!("prototype not found: {indicator}"));

    let after = &header[start + needle.len()..];

    let end = after
        .find(')')
        .unwrap_or_else(|| panic!("no closing paren for {indicator}"));

    let params: Vec<&str> = after[..end]
        .split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .collect();

    let mut f = TA_Lib {
        indicator: indicator.to_string(),
        argument_type: "TA_DOUBLE",
        ..Default::default()
    };

    for p in &params {
        // skip TA_INDICATOR(int startIdx, int endIdx, ...)
        if p.contains("startIdx") || p.contains("endIdx") {
            continue;
        }
        // skip TA_INDICATOR(..., int *outBegIdx, int *outNBElement, ...)
        if p.contains("outBegIdx") || p.contains("outNBElement") {
            continue;
        }

        // The TA_INDICATOR contains two types
        // of arrays - immutable input arrays, and mutable
        // output arrays. Input arrays are *always* doubles
        // while output can be integer arrays (candlestick patterns)
        if p.contains("[]") {
            let nm = parameter_identifier(p);

            if p.contains("const") {
                f.input.push(nm);
            } else {
                f.argument_type = if p.contains("double") {
                    "TA_DOUBLE"
                } else {
                    "TA_INTEGER"
                };
                f.output_indicators.push(nm);
            }
        } else {
            // the remainder of the TA_INDICATOR(..., int optInTimePeriod, ...)
            // can either be a double, integer or MAType
            let nm = parameter_identifier(p);

            f.optional_input.push(if p.contains("TA_MAType") {
                format!("OPTIONAL_MATYPE({nm})")
            } else if p.contains("double") {
                format!("OPTIONAL_DOUBLE({nm})")
            } else {
                format!("OPTIONAL_INTEGER({nm})")
            });
        }
    }

    // The output names are given as outReal, outRealUpperBand
    // which needs to be stripped so it ouputs UpperBand and
    // for univariate output where outReal is not identifiable
    // from the outputs the indicator name is replaced so
    // outReal becomes SMA for TA_SMA()
    for output in &f.output_indicators {
        let bare = output.strip_prefix("out").unwrap_or(output);
        let bare = bare.strip_prefix("Real").unwrap_or(bare);
        let bare = bare.strip_prefix("Integer").unwrap_or(bare);

        f.output_names.push(if bare.is_empty() {
            f.indicator.clone()
        } else {
            bare.to_string()
        });
    }
    f
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "
        TA_LIB_API TA_RetCode TA_RSI(
            int startIdx,
            int endIdx,
            const double inReal[],
            int optInTimePeriod,
            int *outBegIdx,
            int *outNBElement,
            double outReal[]
        );

        TA_LIB_API TA_RetCode TA_BBANDS(
            int startIdx, int endIdx,
            const double inReal[],
            int optInTimePeriod,
            double optInNbDevUp,
            double optInNbDevDn,
            TA_MAType optInMAType,
            int *outBegIdx,
            int *outNBElement,
            double outRealUpperBand[],
            double outRealMiddleBand[],
            double outRealLowerBand[]
        );

        TA_LIB_API TA_RetCode TA_CDLDOJI(
            int startIdx,
            int endIdx,
            const double inOpen[],
            const double inHigh[],
            const double inLow[],
            const double inClose[],
            int *outBegIdx,
            int *outNBElement,
            int outInteger[]
        );
    ";

    #[test]
    fn parses_single_real() {
        let f = extract_signature("RSI", SAMPLE);
        assert_eq!(f.argument_type, "TA_DOUBLE");
        assert_eq!(f.input, ["inReal"]);
        assert_eq!(f.optional_input, ["OPTIONAL_INTEGER(optInTimePeriod)"]);
        assert_eq!(f.output_indicators, ["outReal"]);
        assert_eq!(f.output_names, ["RSI"]);
    }

    #[test]
    fn parses_multi_out_and_matypes() {
        let f = extract_signature("BBANDS", SAMPLE);
        assert_eq!(f.input, ["inReal"]);
        assert_eq!(
            f.optional_input,
            [
                "OPTIONAL_INTEGER(optInTimePeriod)",
                "OPTIONAL_DOUBLE(optInNbDevUp)",
                "OPTIONAL_DOUBLE(optInNbDevDn)",
                "OPTIONAL_MATYPE(optInMAType)"
            ]
        );
        assert_eq!(
            f.output_indicators,
            ["outRealUpperBand", "outRealMiddleBand", "outRealLowerBand"]
        );
        assert_eq!(f.output_names, ["UpperBand", "MiddleBand", "LowerBand"]);
    }

    #[test]
    fn parses_int_output_and_ohlc() {
        let f = extract_signature("CDLDOJI", SAMPLE);
        assert_eq!(f.argument_type, "TA_INTEGER");
        assert_eq!(f.input, ["inOpen", "inHigh", "inLow", "inClose"]);
        assert!(f.optional_input.is_empty());
        assert_eq!(f.output_indicators, ["outInteger"]);
        assert_eq!(f.output_names, ["CDLDOJI"]);
    }

    #[test]
    fn renders_macro_lines() {
        let purged = purge_comments(SAMPLE);

        assert_eq!(
            indicator_macro(&extract_signature("RSI", &purged)),
            "TA_INDICATOR(RSI, TA_DOUBLE, TA_INPUT(inReal), \
             TA_OPTIONS(OPTIONAL_INTEGER(optInTimePeriod)), TA_OUTPUT(outReal), \
             TA_OUTPUT_NAME(RSI), NOT_CANDLESTICK)"
        );
        assert_eq!(
            lookback_macro(&extract_signature("RSI", &purged)),
            "TA_LOOKBACK(RSI, TA_OPTIONS(OPTIONAL_INTEGER(optInTimePeriod)))"
        );

        // candlesticks carry the CANDLESTICK kind (normalization flag)
        // and an empty TA_OPTIONS()
        assert_eq!(
            indicator_macro(&extract_signature("CDLDOJI", &purged)),
            "TA_INDICATOR(CDLDOJI, TA_INTEGER, TA_INPUT(inOpen, inHigh, inLow, inClose), \
             TA_OPTIONS(), TA_OUTPUT(outInteger), TA_OUTPUT_NAME(CDLDOJI), CANDLESTICK)"
        );
    }

    #[test]
    fn strips_comments() {
        assert_eq!(purge_comments("a /* x */ b"), "a   b");
    }
}
