// load the parser
mod parser;
use parser::purge_comments;
use std::fs;

use crate::parser::{TA_Lib, extract_signature};

/// BATCH_INDICATOR_MACRO
///
/// TA_INDICATOR: The indicator function of TA-Lib, e.g. TA_SMA() and its type
/// TA_INPUT: The input to the TA-Lib indicator, e.g. inReal
/// TA_OPTIONS: The optional input in the TA-Lib indicator, e.g. optInWindow
/// TA_OUTPUT: The output from the TA-Lib indicator, e.g. outReal
/// TA_OUTPUT_NAME: The output names from the TA-Lib indicator, e.g. outReal, outRealMiddleBand etc.
#[allow(non_snake_case)]
fn BATCH_INDICATOR_MACRO(function: &TA_Lib) -> String {
    format!(
        "TA_INDICATOR({}, {}, TA_INPUT({}), TA_OPTIONS({}), TA_OUTPUT({}), TA_OUTPUT_NAME({}), {})",
        function.indicator,
        function.argument_type,
        function.input.join(", "),
        function.optional_input.join(", "),
        function.output_indicators.join(", "),
        function.output_names.join(", "),
        if function.indicator.starts_with("CDL") {
            "CANDLESTICK"
        } else {
            "NOT_CANDLESTICK"
        }
    )
}

/// LOOKBACK_MACRO
///
/// The TA_<indicator>_Lookback() companion of each indicator takes exactly the
/// indicator's optional inputs, so its macro only needs the name and TA_OPTIONS.
/// Void lookbacks (e.g. TA_ACOS_Lookback) yield an empty TA_OPTIONS().
#[allow(non_snake_case)]
fn LOOKBACK_MACRO(function: &TA_Lib) -> String {
    format!(
        "TA_LOOKBACK({}, TA_OPTIONS({}))",
        function.indicator,
        function.optional_input.join(", "),
    )
}

///
fn main() {
    // The goal is to write two files (I think)
    let list = fs::read_to_string("src/ta-lib/ta_func_list.txt").expect("read ta_func_list.txt");
    let header = purge_comments(
        &fs::read_to_string("src/ta-lib/include/ta_func.h").expect("read ta_func.h"),
    );

    let names: Vec<String> = list
        .lines()
        .filter_map(|l| l.split_whitespace().next())
        .map(str::to_string)
        .collect();

    let funcs: Vec<TA_Lib> = names
        .iter()
        .map(|n| extract_signature(n, &header))
        .collect();

    // populate the src/TA-Lib.h file
    // with decorative headers that only
    // I will probably read ¯\_(ツ)_/¯
    let mut output = String::new();
    output.push_str("// TA-Lib.h - Autogenerated via codegen/\n");
    output.push_str("// Description:\n//\n");
    output.push_str("// \t\tTA_INDICATOR: TA-Lib indicator.\n");
    output.push_str("// \t\tTA_INPUT: Indicator input.\n");
    output.push_str("// \t\tTA_OPTIONS: Indicator input.\n");
    output.push_str("// \t\tTA_OUTPUT: Indicator input.\n");
    output.push_str("// \t\tTA_OUTPUT_NAMES: Indicator input.\n");
    output.push_str("// \t\tTA_LOOKBACK: Indicator lookback (name + optional inputs).\n");
    output.push_str("//\n");
    output.push_str("// clang-format off\n");

    for f in &funcs {
        output.push_str(&BATCH_INDICATOR_MACRO(f));
        output.push('\n');
    }

    output.push('\n');
    output.push_str("// Lookback\n");
    for f in &funcs {
        output.push_str(&LOOKBACK_MACRO(f));
        output.push('\n');
    }

    output.push_str("// clang-format on\n");

    fs::write("src/TA-Lib.h", output).expect("msg")
}
