//! testthat file generation
//!
//! Renders one testthat file per indicator, written to
//! 'tests/testthat/test-ta_<ALIAS>.R' by main() and overwritten on
//! every run (no protected regions). What a file contains follows
//! from the metadata:
//!
//!   - rolling statistics (GroupId 'Statistic Functions'): a short
//!     fast-track file (',y=SPY[,2]' appended for the bivariate
//!     BETA/CORREL)
//!   - chartable indicators: .plotly/.ggplot method tests, including
//!     candlesticks and moving averages whose chart methods render
//!     from their own templates
//!   - univariate indicators (a single input series): a .numeric
//!     method test

use crate::metadata::MetaData;
use crate::render::render_camel;
use crate::tables::{camel_case_name, chart_type, function_name, is_candlestick, ma_type};

const HEADER: &str = "\
## autogenerated unit-test
## from codegen/
## the file will be overwritten in the next iteration
##
## author: Serkan Korkmaz
";

const ROLLING_TESTS: &str = r#"
## test that the function runs without
## any conditions
testthat::test_that(desc = 'Runs without *any* conditions', code = {

    output <- testthat::expect_no_condition(
		{
			${FUN}(
				x = SPY[,1]${ADDITIONAL}
			)
		}
	)
})

## test that the length of the input
## matches the output
testthat::test_that(desc = 'Length in, length out', code = {
    testthat::expect_equal(
		object = length(
		${FUN}(
			x = SPY[,1]${ADDITIONAL}
		)
		),
		expected = length(SPY[,1])
	)
})

## test that the output is a <double> vector
testthat::test_that(desc = 'Output type', code = {

output <- ${FUN}(
			x = SPY[,1]${ADDITIONAL}
		)

testthat::expect_true(
		typeof(output) == "double" || typeof(output) == "integer"
	)

	testthat::expect_true(
		is.null(dim(output))
	)

})

## test the output's attribute "lookback" matches
## the lookback()
testthat::test_that(desc = 'Lookback equivalence', code = {

output <- attr(
	${FUN}(x = SPY[,1]${ADDITIONAL}),
	"lookback"
)

testthat::expect_equal(
		object = output,
		expected = lookback(FUN = ${FUN}, x = SPY[,1])
	)

}
)
"#;

const STANDARD_TESTS: &str = r#"
## alias and function similarity
## checks this ensures that
## ${FUN} and ${ALIAS} produces the same results
testthat::test_that(desc = 'Alias and function similarity', code = {

    ## 1) test that the alias and
    ##    function returns the same values
    output <- ${FUN}(SPY${PASS_SPY})
    alias  <- ${ALIAS}(SPY${PASS_SPY})

    ## 1.1) check if the values
	##      are equal
	testthat::expect_equal(
		object   = output,
		expected = alias
	)
#camel#
#camel#    ## 2) test that the camelCase alias
#camel#    ##    returns the same values
#camel#    camel <- ${CAMEL}(SPY${PASS_SPY})
#camel#
#camel#    ## 2.1) check if the values
#camel#	##      are equal
#camel#	testthat::expect_equal(
#camel#		object   = output,
#camel#		expected = camel
#camel#	)

})

## type-checks for data.frames and
## matrices
##
## <matrix> object
testthat::test_that(desc = 'Class in, class out (<matrix>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(${FUN}(SPY${PASS_SPY}), class(SPY))
	)

})

## <data.frame> object
testthat::test_that(desc = 'Class in, class out (<data.frame>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(${FUN}(BTC${PASS_BTC}), class(BTC))
	)
})

## check that the default calls
## matches that of the constructed call
## with default values.
##
## NOTE: This test is more of a test of the internal
##       series() function
testthat::test_that(desc = 'Default calls', code = {
    testthat::expect_equal(
		object = ${FUN}(
			BTC${PASS_BTC}
		),
		expected = ${FUN}(
			BTC,
			cols = ${FORMULA}${PASS_BTC}
		)
	)
})

## check that the length of the input
## matches the output length with na.bridge = TRUE
##
## <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame> with na.bridge = TRUE', code = {
    testthat::expect_equal(
		object = nrow(${FUN}(
			ATOM${PASS_ATOM},
			na.bridge = TRUE
		)),
		expected = nrow(ATOM)
	)
})

## check that the rownames are being
## respected for <data.frame> with na.bridge = TRUE
testthat::test_that(desc = 'Row names are respected for <data.frame>, na.bridge = TRUE', code = {
	## extract row names
	x_names <- row.names(ATOM)

	## calculate indicator
	indicator <- ${FUN}(ATOM${PASS_ATOM}, na.bridge = TRUE)

    testthat::expect_equal(
		object = x_names,
		expected = rownames(indicator)
	)
})

## check that the length of the input
## matches the output length
##
## <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame>', code = {
    testthat::expect_equal(
		object = nrow(${FUN}(
			BTC${PASS_BTC}
		)),
		expected = nrow(BTC)
	)
})

## check that the rownames are being
## respected for <data.frame>
testthat::test_that(desc = 'Row names are respected for <data.frame>', code = {
	## extract row names
	x_names <- row.names(BTC)

	## calculate indicator
	indicator <- ${FUN}(BTC${PASS_BTC})

    testthat::expect_equal(
		object = x_names,
		expected = rownames(indicator)
	)
})

## <matrix> object
testthat::test_that(desc = 'Equal length of input and output for <matrix>', code = {
    testthat::expect_equal(
		object = nrow(${FUN}(
			SPY${PASS_SPY}
		)),
		expected = nrow(SPY)
	)
})

## check that the rownames are being
## respected for <matrix>
testthat::test_that(desc = 'Row names are respected for <matrix>', code = {
	## extract row names
	## NOTE: by default the SPY has no
	##       rownames
	rownames(SPY) <- paste0("row",1:nrow(SPY))

	## calculate indicator
	indicator <- ${FUN}(SPY${PASS_SPY})

    testthat::expect_equal(
		object = paste0("row",1:nrow(SPY)),
		expected = rownames(indicator)
	)
})

## test the output's attribute "lookback" matches
## the lookback()
testthat::test_that(desc = 'Lookback equivalence', code = {

output <- attr(
	${FUN}(x = SPY${PASS_SPY}),
	"lookback"
)

testthat::expect_equal(
		object = output,
		expected = lookback(FUN = ${FUN}, x = SPY${PASS_SPY})
	)
#camel#
#camel### the camelCase lookback alias
#camel### is the function itself
#camel#testthat::expect_identical(
#camel#		object = ${CAMEL}_lookback,
#camel#		expected = ${FUN}_lookback
#camel#	)

}
)
"#;

const PLOTLY_TESTS: &str = r#"
## <plotly>-method checks for <data.frame>
## and <matrix>
##
## <data.frame> checks
testthat::test_that(desc = '<plotly>-methods for <data.frame>', code = {
	## check that ${FUN} can
	## use <plotly> without any issues
	output <- testthat::expect_no_error(
		{
			chart(BTC)
			indicator(${FUN}${PASS_BTC})
		}
	)

	## check that the output
	## is a <plotly>-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})

## <matrix> checks
testthat::test_that(desc = '<plotly>-methods for <matrix>', code = {
	## check that ${FUN} can
	## use <plotly> without any issues
	output <- testthat::expect_no_error(
		{
			chart(SPY)
			indicator(${FUN}${PASS_SPY})
		}
	)

	## check that the output
	## is a <plotly>-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})
"#;

const GGPLOT_TESTS: &str = r#"
## <ggplot>-method checks for <data.frame>
## and <matrix>
##
## <data.frame> checks
testthat::test_that(desc = '<ggplot>-methods for <data.frame>', code = {
	testthat::skip_if_not_installed("ggplot2")

	## check that ${FUN} can
	## use <ggplot> without any issues
	output <- testthat::expect_no_error(
		{
			options(talib.chart.backend = "ggplot2")
			on.exit(options(talib.chart.backend = "plotly"))
			chart(BTC)
			indicator(${FUN}${PASS_BTC})
		}
	)

	## check that the output
	## is a <gg>-object or <talib_chart>
	testthat::expect_true(
		inherits(output, "gg") || inherits(output, "talib_chart")
	)
})

## <matrix> checks
testthat::test_that(desc = '<ggplot>-methods for <matrix>', code = {
	testthat::skip_if_not_installed("ggplot2")

	## check that ${FUN} can
	## use <ggplot> without any issues
	output <- testthat::expect_no_error(
		{
			options(talib.chart.backend = "ggplot2")
			on.exit(options(talib.chart.backend = "plotly"))
			chart(SPY)
			indicator(${FUN}${PASS_SPY})
		}
	)

	## check that the output
	## is a <gg>-object or <talib_chart>
	testthat::expect_true(
		inherits(output, "gg") || inherits(output, "talib_chart")
	)
})
"#;

const NUMERIC_TESTS: &str = r#"
## check that <numeric> methods runs without
## issues and returns proper lengths
testthat::test_that(desc = '<numeric> methods', code = {
	## check that the <numeric> method
	## runs
	x <- testthat::expect_no_condition(
		${FUN}(BTC[[1]]${PASS_BTC})
	)

	target_length <- length(BTC[[1]])

	if (NCOL(x) == 1L) {
		testthat::expect_true(is.double(x) || is.integer(x))
		testthat::expect_false(is.matrix(x))
		testthat::expect_equal(length(x), target_length)
	} else {
		testthat::expect_true(is.matrix(x))
		testthat::expect_equal(nrow(x), target_length)
	}
})
"#;

/// Render the testthat file of an indicator
pub fn render_test(f: &MetaData) -> String {
    let fun = function_name(&f.indicator);

    // rolling statistics fast-track: a short univariate file,
    // with the second input series of BETA/CORREL passed as 'y'
    if f.family == "Statistic Functions" || f.family == "Math Operators" {
        let additional = if f.input.len() > 1 { ",y=SPY[,2]" } else { "" };

        return format!(
            "{HEADER}{}",
            ROLLING_TESTS
                .replace("${FUN}", fun)
                .replace("${ADDITIONAL}", additional)
        );
    }

    // passthrough inputs (MAVP: periods) are required formals, so
    // every call site supplies a deterministic full-length vector
    // matched to its dataset via the ${PASS_<DATA>} placeholders
    let pass = |data: &str| {
        f.passthrough
            .iter()
            .map(|p| format!(", {p} = rep(5, nrow({data}))"))
            .collect::<String>()
    };

    // the camelCase alias; single-word indicator names camelCase
    // to themselves, dropping the '#camel#' test lines instead
    let camel = camel_case_name(&f.indicator);
    let has_camel = camel != fun;

    let fill = |template: &str| {
        render_camel(template, has_camel)
            .replace("${FUN}", fun)
            .replace("${ALIAS}", &f.indicator)
            .replace("${CAMEL}", &camel)
            .replace("${FORMULA}", &f.default_formula())
            .replace("${PASS_SPY}", &pass("SPY"))
            .replace("${PASS_BTC}", &pass("BTC"))
            .replace("${PASS_ATOM}", &pass("ATOM"))
    };

    let mut out = format!("{HEADER}{}", fill(STANDARD_TESTS));

    // chartable indicators: candlesticks and moving averages carry
    // their chart methods regardless of CHART_TYPES
    let chartable = chart_type(&f.indicator).is_some()
        || is_candlestick(&f.indicator)
        || ma_type(&f.indicator).is_some();

    if chartable {
        out.push_str(&fill(PLOTLY_TESTS));
        out.push_str(&fill(GGPLOT_TESTS));
    }

    // univariate indicators carry a .numeric method
    if f.input.len() == 1 {
        out.push_str(&fill(NUMERIC_TESTS));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn meta(indicator: &str, family: &str, input: &[&str]) -> MetaData {
        MetaData {
            indicator: indicator.to_string(),
            family: family.to_string(),
            input: input.iter().map(|s| s.to_string()).collect(),
            ..Default::default()
        }
    }

    #[test]
    fn renders_standard_chartable_test() {
        let rendered = render_test(&meta("BBANDS", "Overlap Studies", &["close"]));

        assert!(rendered.contains("output <- bollinger_bands(SPY)"));
        assert!(rendered.contains("alias  <- BBANDS(SPY)"));
        assert!(rendered.contains("camel <- bollingerBands(SPY)"));
        assert!(rendered.contains("object = bollingerBands_lookback,"));
        assert!(!rendered.contains("#camel#"), "unstripped camel prefix");
        assert!(rendered.contains("cols = ~close"));
        assert!(rendered.contains("<plotly>-methods for <data.frame>"));
        assert!(rendered.contains("<ggplot>-methods for <matrix>"));
        assert!(rendered.contains("<numeric> methods"));
        assert!(!rendered.contains("${"), "unreplaced placeholder");
    }

    #[test]
    fn renders_candlestick_test_without_numeric() {
        let rendered = render_test(&meta(
            "CDLDOJI",
            "Pattern Recognition",
            &["open", "high", "low", "close"],
        ));

        assert!(rendered.contains("cols = ~open + high + low + close"));
        assert!(rendered.contains("<plotly>-methods for <data.frame>"));
        assert!(!rendered.contains("<numeric> methods"));

        // 'doji' camelCases to itself:
        // the camel test lines are dropped
        assert!(!rendered.contains("camel <-"));
        assert!(!rendered.contains("#camel#"), "unstripped camel prefix");
    }

    #[test]
    fn renders_passthrough_args() {
        let mut m = meta("MAVP", "Overlap Studies", &["close"]);
        m.passthrough.push("periods".to_string());

        let rendered = render_test(&m);

        // every call site supplies a full-length periods vector
        // matched to its dataset
        assert!(
            rendered.contains("variable_moving_average_period(SPY, periods = rep(5, nrow(SPY)))")
        );
        assert!(rendered.contains("cols = ~close, periods = rep(5, nrow(BTC))"));
        assert!(
            rendered
                .contains("indicator(variable_moving_average_period, periods = rep(5, nrow(BTC)))")
        );
        assert!(
            rendered
                .contains("variable_moving_average_period(BTC[[1]], periods = rep(5, nrow(BTC)))")
        );
        assert!(!rendered.contains("${"), "unreplaced placeholder");
    }

    #[test]
    fn renders_rolling_tests() {
        let rendered = render_test(&meta("STDDEV", "Statistic Functions", &["close"]));

        assert!(rendered.contains("Runs without *any* conditions"));
        assert!(rendered.contains("x = SPY[,1]\n"));
        assert!(!rendered.contains("y=SPY[,2]"));
        assert!(!rendered.contains("Alias and function similarity"));

        // the bivariate rolling statistics pass
        // the second column as 'y'
        let rendered = render_test(&meta("BETA", "Statistic Functions", &["close", "close"]));
        assert!(rendered.contains("x = SPY[,1],y=SPY[,2]"));
    }
}
