#!/usr/bin/env bash
set -euo pipefail

## 1) environment variables
##    to determine unit-tests
FUN=${FUN:?}
TA_FUN=${TA_FUN:?}
ALIAS=${ALIAS:-$TA_FUN}
FORMULA=${FORMULA:-"~close"}
PLOTLY=${PLOTLY:-0}
NUMERIC=${NUMERIC:-1}
OUTPUTFILE=${OUTPUTFILE:-"tests/testthat/test-ta_${TA_FUN}.R"}
ROLLING=${ROLLING:-0}

## 2) fast-track exiting of the
##    program for rolling statistics
if [[ $ROLLING -eq 1 ]]; then

## 2.2) check if the signature includes
##      a 'y' and set it to SPY[[2]]
ADDITIONAL=''
  for a in "$@"; do
    case "$a" in
      y|y=*) ADDITIONAL=',y=SPY[,2]'; break ;;
    esac
done

cat > ${OUTPUTFILE} << EOF
## autogenerated unit-test
## from codegen/generate_unit-tests.sh
## the file will be overwritten in the next iteration
## 
## author: Serkan Korkmaz

## test that the function runs without
## any conditions
testthat::test_that(desc = 'Runs without *any* conditions', code = {

    output <- testthat::expect_no_condition(
		{
			${FUN}(
				x = SPY[,1]${ADDITIONAL}
			)	
		}
	)
})

## test that the length of the input
## matches the output
testthat::test_that(desc = 'Length in, length out', code = {
    testthat::expect_equal(
		object = length(
		${FUN}(
			x = SPY[,1]${ADDITIONAL}
		)
		),
		expected = length(SPY[,1])
	)
})

## test that the output is a <double> vector
testthat::test_that(desc = 'Output type', code = {

output <- ${FUN}(
			x = SPY[,1]${ADDITIONAL}
		)

testthat::expect_true(
		typeof(output) == "double" || typeof(output) == "integer"
	)

	testthat::expect_true(
		is.null(dim(output))
	)

})

## test the output's attribute "lookback" matches
## the lookback()
testthat::test_that(desc = 'Lookback equivalence', code = {

output <- attr(
	${FUN}(x = SPY[,1]${ADDITIONAL}),
	"lookback"
)

testthat::expect_equal(
		object = output,
		expected = lookback(FUN = ${FUN}, x = SPY[,1]${ADDITIONAL})
	)

}
)


EOF

exit 0;
fi

## 1) populate test file
##    with standard stuff
cat > ${OUTPUTFILE} <<EOF
## autogenerated unit-test
## from codegen/generate_unit-tests.sh
## the file will be overwritten in the next iteration
## 
## author: Serkan Korkmaz

## alias and function similarity
## checks this ensures that 
## ${FUN} and ${ALIAS} produces the same results
testthat::test_that(desc = 'Alias and function similarity', code = {

    ## 1) test that the alias and 
    ##    function returns the same values
    output <- ${FUN}(SPY)
    alias  <- ${ALIAS}(SPY)

    ## 1.1) check if the values
	##      are equal
	testthat::expect_equal(
		object   = output,
		expected = alias
	)

})

## type-checks for data.frames and
## matrices
##
## <matrix> object
testthat::test_that(desc = 'Class in, class out (<matrix>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(${FUN}(SPY), class(SPY))
	)

})

## <data.frame> object
testthat::test_that(desc = 'Class in, class out (<data.frame>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(${FUN}(BTC), class(BTC))
	)
})

## check that the default calls
## matches that of the constructed call
## with default values.
##
## NOTE: This test is more of a test of the internal
##       series() function
testthat::test_that(desc = 'Default calls', code = {
    testthat::expect_equal(
		object = ${FUN}(
			BTC
		),
		expected = ${FUN}(
			BTC,
			cols = ${FORMULA}
		)
	)
})

## check that the length of the input
## matches the output length with na.bridge = TRUE
##
## <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame> with na.bridge = TRUE', code = {
    testthat::expect_equal(
		object = nrow(${FUN}(
			ATOM,
			na.bridge = TRUE
		)),
		expected = nrow(ATOM)
	)
})

## check that the rownames are being
## respected for <data.frame> with na.bridge = TRUE
testthat::test_that(desc = 'Row names are respected for <data.frame>, na.bridge = TRUE', code = {
	## extract row names
	x_names <- row.names(ATOM)

	## calculate indicator
	indicator <- ${FUN}(ATOM, na.bridge = TRUE)

    testthat::expect_equal(
		object = x_names,
		expected = rownames(indicator)
	)
})

## check that the length of the input
## matches the output length
##
## <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame>', code = {
    testthat::expect_equal(
		object = nrow(${FUN}(
			BTC
		)),
		expected = nrow(BTC)
	)
})

## check that the rownames are being
## respected for <data.frame>
testthat::test_that(desc = 'Row names are respected for <data.frame>', code = {
	## extract row names
	x_names <- row.names(BTC)

	## calculate indicator
	indicator <- ${FUN}(BTC)

    testthat::expect_equal(
		object = x_names,
		expected = rownames(indicator)
	)
})

## <matrix> object
testthat::test_that(desc = 'Equal length of input and output for <matrix>', code = {
    testthat::expect_equal(
		object = nrow(${FUN}(
			SPY
		)),
		expected = nrow(SPY)
	)
})

## check that the rownames are being
## respected for <matrix>
testthat::test_that(desc = 'Row names are respected for <matrix>', code = {
	## extract row names
	## NOTE: by default the SPY has no
	##       rownames
	rownames(SPY) <- paste0("row",1:nrow(SPY))

	## calculate indicator
	indicator <- ${FUN}(SPY)

    testthat::expect_equal(
		object = paste0("row",1:nrow(SPY)),
		expected = rownames(indicator)
	)
})


## test the output's attribute "lookback" matches
## the lookback()
testthat::test_that(desc = 'Lookback equivalence', code = {

output <- attr(
	${FUN}(SPY),
	"lookback"
)

testthat::expect_equal(
		object = output,
		expected = lookback(FUN = ${FUN}, x = SPY)
	)

}
)

EOF

## Add plotly methods
if [[ $PLOTLY -eq 1 ]]; then
	cat >> ${OUTPUTFILE} <<EOF

## <plotly>-method checks for <data.frame>
## and <matrix>
## 
## <data.frame> checks
testthat::test_that(desc = '<plotly>-methods for <data.frame>', code = {
	## check that ${FUN} can
	## use <plotly> without any issues
	output <- testthat::expect_no_error(
		{
			chart(BTC)
			indicator(${FUN})
		}
	)

	## check that the output
	## is a <plotly>-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})

## <matrix> checks
testthat::test_that(desc = '<plotly>-methods for <matrix>', code = {
	## check that ${FUN} can
	## use <plotly> without any issues
	output <- testthat::expect_no_error(
		{
			chart(SPY)
			indicator(${FUN})
		}
	)

	## check that the output
	## is a <plotly>-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})
EOF
fi

## Add ggplot2 methods
if [[ $PLOTLY -eq 1 ]]; then
	cat >> ${OUTPUTFILE} <<EOF

## <ggplot>-method checks for <data.frame>
## and <matrix>
##
## <data.frame> checks
testthat::test_that(desc = '<ggplot>-methods for <data.frame>', code = {
	testthat::skip_if_not_installed("ggplot2")

	## check that ${FUN} can
	## use <ggplot> without any issues
	output <- testthat::expect_no_error(
		{
			options(talib.chart.backend = "ggplot2")
			on.exit(options(talib.chart.backend = "plotly"))
			chart(BTC)
			indicator(${FUN})
		}
	)

	## check that the output
	## is a <gg>-object or <talib_chart>
	testthat::expect_true(
		inherits(output, "gg") || inherits(output, "talib_chart")
	)
})

## <matrix> checks
testthat::test_that(desc = '<ggplot>-methods for <matrix>', code = {
	testthat::skip_if_not_installed("ggplot2")

	## check that ${FUN} can
	## use <ggplot> without any issues
	output <- testthat::expect_no_error(
		{
			options(talib.chart.backend = "ggplot2")
			on.exit(options(talib.chart.backend = "plotly"))
			chart(SPY)
			indicator(${FUN})
		}
	)

	## check that the output
	## is a <gg>-object or <talib_chart>
	testthat::expect_true(
		inherits(output, "gg") || inherits(output, "talib_chart")
	)
})
EOF
fi

## add <numeric> methods
if [[ $NUMERIC -eq 1 ]]; then
	cat >> ${OUTPUTFILE} <<EOF

## check that <numeric> methods runs without
## issues and returns proper lengths
testthat::test_that(desc = '<numeric> methods', code = {
	## check that the <numeric> method
	## runs
	x <- testthat::expect_no_condition(
		${FUN}(BTC[[1]])
	)

	target_length <- length(BTC[[1]])

	if (NCOL(x) == 1L) {
		testthat::expect_true(is.double(x) || is.integer(x))
		testthat::expect_false(is.matrix(x))
		testthat::expect_equal(length(x), target_length)
	} else {
		testthat::expect_true(is.matrix(x))
		testthat::expect_equal(nrow(x), target_length)
	}
})
EOF
fi
