## testthat helper - sourced automatically before the test files
##
## MAVP (variable_moving_average_period) consumes a 'periods' column
## alongside 'close' (default formula ~close + periods), but the
## built-in datasets ship without one. The autogenerated tests call
## every indicator on the bare datasets, so shadow them here with
## copies carrying a deterministic 'periods' column. Harmless for the
## remaining indicators - they select their columns via formula and
## ignore the extra column.
.add_periods <- function(x) {
	periods <- rep_len(
		x = 5:10,
		length.out = nrow(x)
	)

	if (is.matrix(x)) {
		return(
			cbind(x, periods = periods)
		)
	}

	x$periods <- periods

	x
}

BTC <- .add_periods(talib::BTC)
SPY <- .add_periods(talib::SPY)
ATOM <- .add_periods(talib::ATOM)
