## autogenerated unit-test
## from codegen/
## the file will be overwritten in the next iteration
##
## author: Serkan Korkmaz

## alias and function similarity
## checks this ensures that
## volume_weighted_moving_average and VWMA produces the same results
testthat::test_that(desc = 'Alias and function similarity', code = {
	## 1) test that the alias and
	##    function returns the same values
	output <- volume_weighted_moving_average(SPY)
	alias <- VWMA(SPY)

	## 1.1) check if the values
	##      are equal
	testthat::expect_equal(
		object = output,
		expected = alias
	)

	## 2) test that the camelCase alias
	##    returns the same values
	camel <- volumeWeightedMovingAverage(SPY)

	## 2.1) check if the values
	##      are equal
	testthat::expect_equal(
		object = output,
		expected = camel
	)
})

## type-checks for data.frames and
## matrices
##
## <matrix> object
testthat::test_that(desc = 'Class in, class out (<matrix>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(volume_weighted_moving_average(SPY), class(SPY))
	)
})

## <data.frame> object
testthat::test_that(desc = 'Class in, class out (<data.frame>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(volume_weighted_moving_average(BTC), class(BTC))
	)
})

## check that the default calls
## matches that of the constructed call
## with default values.
##
## NOTE: This test is more of a test of the internal
##       series() function
testthat::test_that(desc = 'Default calls', code = {
	testthat::expect_equal(
		object = volume_weighted_moving_average(
			BTC
		),
		expected = volume_weighted_moving_average(
			BTC,
			cols = ~ close + volume
		)
	)
})

## check that the length of the input
## matches the output length with na.bridge = TRUE
##
## <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame> with na.bridge = TRUE', code = {
	testthat::expect_equal(
		object = nrow(volume_weighted_moving_average(
			ATOM,
			na.bridge = TRUE
		)),
		expected = nrow(ATOM)
	)
})

## check that the rownames are being
## respected for <data.frame> with na.bridge = TRUE
testthat::test_that(desc = 'Row names are respected for <data.frame>, na.bridge = TRUE', code = {
	## extract row names
	x_names <- row.names(ATOM)

	## calculate indicator
	indicator <- volume_weighted_moving_average(ATOM, na.bridge = TRUE)

	testthat::expect_equal(
		object = x_names,
		expected = rownames(indicator)
	)
})

## check that the length of the input
## matches the output length
##
## <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame>', code = {
	testthat::expect_equal(
		object = nrow(volume_weighted_moving_average(
			BTC
		)),
		expected = nrow(BTC)
	)
})

## check that the rownames are being
## respected for <data.frame>
testthat::test_that(desc = 'Row names are respected for <data.frame>', code = {
	## extract row names
	x_names <- row.names(BTC)

	## calculate indicator
	indicator <- volume_weighted_moving_average(BTC)

	testthat::expect_equal(
		object = x_names,
		expected = rownames(indicator)
	)
})

## <matrix> object
testthat::test_that(desc = 'Equal length of input and output for <matrix>', code = {
	testthat::expect_equal(
		object = nrow(volume_weighted_moving_average(
			SPY
		)),
		expected = nrow(SPY)
	)
})

## check that the rownames are being
## respected for <matrix>
testthat::test_that(desc = 'Row names are respected for <matrix>', code = {
	## extract row names
	## NOTE: by default the SPY has no
	##       rownames
	rownames(SPY) <- paste0("row", 1:nrow(SPY))

	## calculate indicator
	indicator <- volume_weighted_moving_average(SPY)

	testthat::expect_equal(
		object = paste0("row", 1:nrow(SPY)),
		expected = rownames(indicator)
	)
})

## test the output's attribute "lookback" matches
## the lookback()
testthat::test_that(desc = 'Lookback equivalence', code = {
	output <- attr(
		volume_weighted_moving_average(x = SPY),
		"lookback"
	)

	testthat::expect_equal(
		object = output,
		expected = lookback(FUN = volume_weighted_moving_average, x = SPY)
	)

	## the camelCase lookback alias
	## is the function itself
	testthat::expect_identical(
		object = volumeWeightedMovingAverage_lookback,
		expected = volume_weighted_moving_average_lookback
	)
})

## <plotly>-method checks for <data.frame>
## and <matrix>
##
## <data.frame> checks
testthat::test_that(desc = '<plotly>-methods for <data.frame>', code = {
	## check that volume_weighted_moving_average can
	## use <plotly> without any issues
	output <- testthat::expect_no_error(
		{
			chart(BTC)
			indicator(volume_weighted_moving_average)
		}
	)

	## check that the output
	## is a <plotly>-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})

## <matrix> checks
testthat::test_that(desc = '<plotly>-methods for <matrix>', code = {
	## check that volume_weighted_moving_average can
	## use <plotly> without any issues
	output <- testthat::expect_no_error(
		{
			chart(SPY)
			indicator(volume_weighted_moving_average)
		}
	)

	## check that the output
	## is a <plotly>-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})

## <ggplot>-method checks for <data.frame>
## and <matrix>
##
## <data.frame> checks
testthat::test_that(desc = '<ggplot>-methods for <data.frame>', code = {
	testthat::skip_if_not_installed("ggplot2")

	## check that volume_weighted_moving_average can
	## use <ggplot> without any issues
	output <- testthat::expect_no_error(
		{
			options(talib.chart.backend = "ggplot2")
			on.exit(options(talib.chart.backend = "plotly"))
			chart(BTC)
			indicator(volume_weighted_moving_average)
		}
	)

	## check that the output
	## is a <gg>-object or <talib_chart>
	testthat::expect_true(
		inherits(output, "gg") || inherits(output, "talib_chart")
	)
})

## <matrix> checks
testthat::test_that(desc = '<ggplot>-methods for <matrix>', code = {
	testthat::skip_if_not_installed("ggplot2")

	## check that volume_weighted_moving_average can
	## use <ggplot> without any issues
	output <- testthat::expect_no_error(
		{
			options(talib.chart.backend = "ggplot2")
			on.exit(options(talib.chart.backend = "plotly"))
			chart(SPY)
			indicator(volume_weighted_moving_average)
		}
	)

	## check that the output
	## is a <gg>-object or <talib_chart>
	testthat::expect_true(
		inherits(output, "gg") || inherits(output, "talib_chart")
	)
})
