## autogenerated unit-test
## from tools/generate_unit-tests.sh
## the file will be overwritten in the next iteration
##
## author: Serkan Korkmaz

## 1) alias and function similarity
##    checks this ensures that
##    midpoint_price and MIDPRICE produces the same results
testthat::test_that(desc = 'Alias and function similarity', code = {
	## 1) test that the alias and
	##    function returns the same values
	output <- midpoint_price(SPY)
	alias <- MIDPRICE(SPY)

	## 1.1) check if the values
	##      are equal
	testthat::expect_equal(
		object = output,
		expected = alias
	)
})

## 3) type-checks for data.frames and
##    matrices
##
## 3.1) <matrix> object
testthat::test_that(desc = 'Class in, class out (<matrix>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(midpoint_price(SPY), class(SPY))
	)
})

## 3.2) <data.frame> object
testthat::test_that(desc = 'Class in, class out (<data.frame>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(midpoint_price(BTC), class(BTC))
	)
})

## 4) check that the default calls
##    matches that of the constructed call
##    with default values.
##
##    NOTE: This test is more of a test of the internal
##          series() function
testthat::test_that(desc = 'Default calls', code = {
	testthat::expect_equal(
		object = midpoint_price(
			BTC
		),
		expected = midpoint_price(
			BTC,
			cols = ~ high + low
		)
	)
})

## 5) check that the lenght of the input
##    matches the output length
##
## 5.1) <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame>', code = {
	testthat::expect_equal(
		object = nrow(midpoint_price(
			BTC
		)),
		expected = nrow(BTC)
	)
})

## 5.2) <matrix> object
testthat::test_that(desc = 'Equal length of input and output for <matrix>', code = {
	testthat::expect_equal(
		object = nrow(midpoint_price(
			SPY
		)),
		expected = nrow(SPY)
	)
})
