## autogenerated unit-test
## from tools/generate_unit-tests.sh
## the file will be overwritten in the next iteration
##
## author: Serkan Korkmaz

## alias and function similarity
## checks this ensures that
## ratio_of_change and ROCR produces the same results
testthat::test_that(desc = 'Alias and function similarity', code = {
	## 1) test that the alias and
	##    function returns the same values
	output <- ratio_of_change(SPY)
	alias <- ROCR(SPY)

	## 1.1) check if the values
	##      are equal
	testthat::expect_equal(
		object = output,
		expected = alias
	)
})

## type-checks for data.frames and
## matrices
##
## <matrix> object
testthat::test_that(desc = 'Class in, class out (<matrix>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(ratio_of_change(SPY), class(SPY))
	)
})

## <data.frame> object
testthat::test_that(desc = 'Class in, class out (<data.frame>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(ratio_of_change(BTC), class(BTC))
	)
})

## check that the default calls
## matches that of the constructed call
## with default values.
##
## NOTE: This test is more of a test of the internal
##       series() function
testthat::test_that(desc = 'Default calls', code = {
	testthat::expect_equal(
		object = ratio_of_change(
			BTC
		),
		expected = ratio_of_change(
			BTC,
			cols = ~close
		)
	)
})

## check that the lenght of the input
## matches the output length
##
## <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame>', code = {
	testthat::expect_equal(
		object = nrow(ratio_of_change(
			BTC
		)),
		expected = nrow(BTC)
	)
})

## <matrix> object
testthat::test_that(desc = 'Equal length of input and output for <matrix>', code = {
	testthat::expect_equal(
		object = nrow(ratio_of_change(
			SPY
		)),
		expected = nrow(SPY)
	)
})


## <plotly>-method checks for <data.frame>
## and <matrix>
##
## <data.frame> checks
testthat::test_that(desc = '<plotly>-methods for <data.frame>', code = {
	## check that ratio_of_change can
	## use <plotly> without any issues
	output <- testthat::expect_no_error(
		{
			chart(BTC)
			indicator(ratio_of_change)
		}
	)

	## check that the output
	## is a <plotly>-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})

## <matrix> checks
testthat::test_that(desc = '<plotly>-methods for <matrix>', code = {
	## check that ratio_of_change can
	## use <plotly> without any issues
	output <- testthat::expect_no_error(
		{
			chart(SPY)
			indicator(ratio_of_change)
		}
	)

	## check that the output
	## is a <plotly>-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})

## check that <numeric> methods runs without
## issues and returns proper lengths
testthat::test_that(desc = '<numeric> methods', code = {
	## check that the <numeric> method
	## runs
	x <- testthat::expect_no_condition(
		ratio_of_change(BTC[[1]])
	)

	## the numeric methods returns <matrix>
	## depending on the underlying functions
	## so the checks for equal lengths is conditional
	target_length <- length(BTC[[1]])

	if (is.null(dim(x))) {
		testthat::expect_true(
			length(x) == target_length
		)
	} else {
		testthat::expect_true(
			nrow(x) == target_length
		)
	}
})
