## autogenerated unit-test
## from codegen/
## the file will be overwritten in the next iteration
##
## author: Serkan Korkmaz

## alias and function similarity
## checks this ensures that
## dominant_cycle_phase and HT_DCPHASE produces the same results
testthat::test_that(desc = 'Alias and function similarity', code = {
	## 1) test that the alias and
	##    function returns the same values
	output <- dominant_cycle_phase(SPY)
	alias <- HT_DCPHASE(SPY)

	## 1.1) check if the values
	##      are equal
	testthat::expect_equal(
		object = output,
		expected = alias
	)

	## 2) test that the camelCase alias
	##    returns the same values
	camel <- dominantCyclePhase(SPY)

	## 2.1) check if the values
	##      are equal
	testthat::expect_equal(
		object = output,
		expected = camel
	)
})

## type-checks for data.frames and
## matrices
##
## <matrix> object
testthat::test_that(desc = 'Class in, class out (<matrix>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(dominant_cycle_phase(SPY), class(SPY))
	)
})

## <data.frame> object
testthat::test_that(desc = 'Class in, class out (<data.frame>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(dominant_cycle_phase(BTC), class(BTC))
	)
})

## <xts> object
testthat::test_that(desc = 'Class in, class out (<xts>)', code = {
	testthat::skip_if_not_installed("xts")

	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(dominant_cycle_phase(GOOGL), class(GOOGL))
	)
})

## the <xts> path must select the same columns in the
## same order as the <data.frame> reference, regardless
## of the physical column layout
testthat::test_that(desc = 'Value parity with <data.frame> (<xts>)', code = {
	testthat::skip_if_not_installed("xts")

	## lowercase <data.frame> reference
	## from the GOOGL fixture
	reference <- as.data.frame(GOOGL)
	colnames(reference) <- tolower(sub("^GOOGL\\.", "", colnames(reference)))
	reference <- unname(as.matrix(dominant_cycle_phase(reference)))

	testthat::expect_equal(
		object = unname(zoo::coredata(dominant_cycle_phase(GOOGL))),
		expected = reference
	)

	## alphabetically sorted columns place 'Adjusted'
	## first and must resolve identically
	testthat::expect_equal(
		object = unname(zoo::coredata(dominant_cycle_phase(GOOGL[, sort(colnames(
			GOOGL
		))]))),
		expected = reference
	)
})

## check that the default calls
## matches that of the constructed call
## with default values.
##
## NOTE: This test is more of a test of the internal
##       series() function
testthat::test_that(desc = 'Default calls', code = {
	testthat::expect_equal(
		object = dominant_cycle_phase(
			BTC
		),
		expected = dominant_cycle_phase(
			BTC,
			cols = ~close
		)
	)
})

## check that the length of the input
## matches the output length with na.bridge = TRUE
##
## <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame> with na.bridge = TRUE', code = {
	testthat::expect_equal(
		object = nrow(dominant_cycle_phase(
			ATOM,
			na.bridge = TRUE
		)),
		expected = nrow(ATOM)
	)
})

## check that the rownames are being
## respected for <data.frame> with na.bridge = TRUE
testthat::test_that(desc = 'Row names are respected for <data.frame>, na.bridge = TRUE', code = {
	## extract row names
	x_names <- row.names(ATOM)

	## calculate indicator
	indicator <- dominant_cycle_phase(ATOM, na.bridge = TRUE)

	testthat::expect_equal(
		object = x_names,
		expected = rownames(indicator)
	)
})

## check that the length of the input
## matches the output length
##
## <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame>', code = {
	testthat::expect_equal(
		object = nrow(dominant_cycle_phase(
			BTC
		)),
		expected = nrow(BTC)
	)
})

## check that the rownames are being
## respected for <data.frame>
testthat::test_that(desc = 'Row names are respected for <data.frame>', code = {
	## extract row names
	x_names <- row.names(BTC)

	## calculate indicator
	indicator <- dominant_cycle_phase(BTC)

	testthat::expect_equal(
		object = x_names,
		expected = rownames(indicator)
	)
})

## <matrix> object
testthat::test_that(desc = 'Equal length of input and output for <matrix>', code = {
	testthat::expect_equal(
		object = nrow(dominant_cycle_phase(
			SPY
		)),
		expected = nrow(SPY)
	)
})

## check that the rownames are being
## respected for <matrix>
testthat::test_that(desc = 'Row names are respected for <matrix>', code = {
	## extract row names
	## NOTE: by default the SPY has no
	##       rownames
	rownames(SPY) <- paste0("row", 1:nrow(SPY))

	## calculate indicator
	indicator <- dominant_cycle_phase(SPY)

	testthat::expect_equal(
		object = paste0("row", 1:nrow(SPY)),
		expected = rownames(indicator)
	)
})

## test the output's attribute "lookback" matches
## the lookback()
testthat::test_that(desc = 'Lookback equivalence', code = {
	output <- attr(
		dominant_cycle_phase(x = SPY),
		"lookback"
	)

	testthat::expect_equal(
		object = output,
		expected = lookback(FUN = dominant_cycle_phase, x = SPY)
	)

	## the camelCase lookback alias
	## is the function itself
	testthat::expect_identical(
		object = talib:::dominantCyclePhase_lookback,
		expected = talib:::dominant_cycle_phase_lookback
	)
})

## <plotly>-method checks for <data.frame>
## and <matrix>
##
## <data.frame> checks
testthat::test_that(desc = '<plotly>-methods for <data.frame>', code = {
	## check that dominant_cycle_phase can
	## use <plotly> without any issues
	output <- testthat::expect_no_error(
		{
			chart(BTC)
			indicator(dominant_cycle_phase)
		}
	)

	## check that the output
	## is a <plotly>-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})

## <matrix> checks
testthat::test_that(desc = '<plotly>-methods for <matrix>', code = {
	## check that dominant_cycle_phase can
	## use <plotly> without any issues
	output <- testthat::expect_no_error(
		{
			chart(SPY)
			indicator(dominant_cycle_phase)
		}
	)

	## check that the output
	## is a <plotly>-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})

## <ggplot>-method checks for <data.frame>
## and <matrix>
##
## <data.frame> checks
testthat::test_that(desc = '<ggplot>-methods for <data.frame>', code = {
	testthat::skip_if_not_installed("ggplot2")

	## check that dominant_cycle_phase can
	## use <ggplot> without any issues
	output <- testthat::expect_no_error(
		{
			options(talib.chart.backend = "ggplot2")
			on.exit(options(talib.chart.backend = "plotly"))
			chart(BTC)
			indicator(dominant_cycle_phase)
		}
	)

	## check that the output
	## is a <gg>-object or <talib_chart>
	testthat::expect_true(
		inherits(output, "gg") || inherits(output, "talib_chart")
	)
})

## <matrix> checks
testthat::test_that(desc = '<ggplot>-methods for <matrix>', code = {
	testthat::skip_if_not_installed("ggplot2")

	## check that dominant_cycle_phase can
	## use <ggplot> without any issues
	output <- testthat::expect_no_error(
		{
			options(talib.chart.backend = "ggplot2")
			on.exit(options(talib.chart.backend = "plotly"))
			chart(SPY)
			indicator(dominant_cycle_phase)
		}
	)

	## check that the output
	## is a <gg>-object or <talib_chart>
	testthat::expect_true(
		inherits(output, "gg") || inherits(output, "talib_chart")
	)
})

## check that <numeric> methods runs without
## issues and returns proper lengths
testthat::test_that(desc = '<numeric> methods', code = {
	## check that the <numeric> method
	## runs
	x <- testthat::expect_no_condition(
		dominant_cycle_phase(BTC[[1]])
	)

	target_length <- length(BTC[[1]])

	if (NCOL(x) == 1L) {
		testthat::expect_true(is.double(x) || is.integer(x))
		testthat::expect_false(is.matrix(x))
		testthat::expect_false(inherits(x, "matrix"))
		testthat::expect_equal(length(x), target_length)
	} else {
		testthat::expect_true(is.matrix(x))
		testthat::expect_identical(class(x), c("matrix", "array"))
		testthat::expect_equal(nrow(x), target_length)
	}
})
