## autogenerated unit-test
## from codegen/
## the file will be overwritten in the next iteration
##
## author: Serkan Korkmaz

## test that the function runs without
## any conditions
testthat::test_that(desc = 'Runs without *any* conditions', code = {
	output <- testthat::expect_no_condition(
		{
			rolling_maximum(
				x = SPY[, 1]
			)
		}
	)
})

## test that the length of the input
## matches the output
testthat::test_that(desc = 'Length in, length out', code = {
	testthat::expect_equal(
		object = length(
			rolling_maximum(
				x = SPY[, 1]
			)
		),
		expected = length(SPY[, 1])
	)
})

## test that the output is a <double> vector
testthat::test_that(desc = 'Output type', code = {
	output <- rolling_maximum(
		x = SPY[, 1]
	)

	testthat::expect_true(
		typeof(output) == "double" || typeof(output) == "integer"
	)

	testthat::expect_true(
		is.null(dim(output))
	)
})

## test the output's attribute "lookback" matches
## the lookback()
testthat::test_that(desc = 'Lookback equivalence', code = {
	output <- attr(
		rolling_maximum(x = SPY[, 1]),
		"lookback"
	)

	testthat::expect_equal(
		object = output,
		expected = lookback(FUN = rolling_maximum, x = SPY[, 1])
	)
})

## <xts> object
testthat::test_that(desc = 'Class in, class out (<xts>)', code = {
	testthat::skip_if_not_installed("xts")

	output <- rolling_maximum(x = GOOGL[, 1])

	testthat::expect_true(inherits(output, "xts"))
	testthat::expect_equal(zoo::index(output), zoo::index(GOOGL))
	testthat::expect_equal(
		object = as.numeric(output),
		expected = as.numeric(rolling_maximum(x = as.numeric(GOOGL[, 1])))
	)
})

## multi-column input must error
## instead of being flattened
testthat::test_that(desc = 'Multivariate input errors', code = {
	testthat::skip_if_not_installed("xts")

	testthat::expect_error(rolling_maximum(x = GOOGL))
	testthat::expect_error(rolling_maximum(x = SPY))
})
