
## autogenerated unit-test
## from tools/generate_unit-tests.sh
## the file will be overwritten in the next iteration
## 
## author: Serkan Korkmaz
## updated: 2025-10-18

## 1) alias and function similarity
##    checks this ensures that 
##    CDL3STARSINSOUTH and three_stars_in_the_south produces the same results
testthat::test_that(desc = 'Alias and function similarity', code = {

    ## 1) test that the alias and 
    ##    function returns the same values
    output <- CDL3STARSINSOUTH(SPY)
    alias  <- three_stars_in_the_south(SPY)

    ## 1.1) check if the values
	##      are equal
	testthat::expect_equal(
		object   = output,
		expected = alias
	)

})

## 2) {plotly}-method checks for data.frames
##    and matrices
## 
## 2.1) data.frame checks
testthat::test_that(desc = '{plotly}-methods for <data.frame>', code = {
    ## 1) check that CDL3STARSINSOUTH can
	##    use {plotly} without any issues
	output <- testthat::expect_no_error(
		{
			chart(BTC)
			indicator(CDL3STARSINSOUTH)
		}
	)

	## 1.1) check that the output
	##      is a {plotly}-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})

## 2.2) matrix checks
testthat::test_that(desc = '{plotly}-methods for <matrix>', code = {
    ## 1) check that CDL3STARSINSOUTH can
	##    use {plotly} without any issues
	output <- testthat::expect_no_error(
		{
			chart(SPY)
			indicator(CDL3STARSINSOUTH)
		}
	)

	## 1.1) check that the output
	##      is a {plotly}-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})

## 3) type-checks for data.frames and
##    matrices
##
## 3.1) <matrix> object
testthat::test_that(desc = 'Class in, class out (<matrix>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(CDL3STARSINSOUTH(SPY), class(SPY))
	)

})

## 3.2) <data.frame> object
testthat::test_that(desc = 'Class in, class out (<data.frame>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(CDL3STARSINSOUTH(BTC), class(BTC))
	)
})

## 4) check that the default calls
##    matches that of the constructed call
##    with default values.
##
##    NOTE: This test is more of a test of the internal
##          series() function
testthat::test_that(desc = 'Default calls', code = {
    testthat::expect_equal(
		object = CDL3STARSINSOUTH(
			BTC
		),
		expected = CDL3STARSINSOUTH(
			BTC,
			cols = ~open+high+low+close
		)
	)
})

## 5) check that the lenght of the input
##    matches the output length
testthat::test_that(desc = 'Equal length of input and output', code = {
    testthat::expect_equal(
		object = nrow(CDL3STARSINSOUTH(
			BTC
		)),
		expected = nrow(BTC)
	)
})

