## autogenerated unit-test
## from codegen/
## the file will be overwritten in the next iteration
##
## author: Serkan Korkmaz

## alias and function similarity
## checks this ensures that
## MIDPOINT and MIDPOINT produces the same results
testthat::test_that(desc = 'Alias and function similarity', code = {
	## 1) test that the alias and
	##    function returns the same values
	output <- MIDPOINT(SPY)
	alias <- MIDPOINT(SPY)

	## 1.1) check if the values
	##      are equal
	testthat::expect_equal(
		object = output,
		expected = alias
	)
})

## type-checks for data.frames and
## matrices
##
## <matrix> object
testthat::test_that(desc = 'Class in, class out (<matrix>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(MIDPOINT(SPY), class(SPY))
	)
})

## <data.frame> object
testthat::test_that(desc = 'Class in, class out (<data.frame>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(MIDPOINT(BTC), class(BTC))
	)
})

## check that the default calls
## matches that of the constructed call
## with default values.
##
## NOTE: This test is more of a test of the internal
##       series() function
testthat::test_that(desc = 'Default calls', code = {
	testthat::expect_equal(
		object = MIDPOINT(
			BTC
		),
		expected = MIDPOINT(
			BTC,
			cols = ~close
		)
	)
})

## check that the length of the input
## matches the output length with na.bridge = TRUE
##
## <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame> with na.bridge = TRUE', code = {
	testthat::expect_equal(
		object = nrow(MIDPOINT(
			ATOM,
			na.bridge = TRUE
		)),
		expected = nrow(ATOM)
	)
})

## check that the rownames are being
## respected for <data.frame> with na.bridge = TRUE
testthat::test_that(desc = 'Row names are respected for <data.frame>, na.bridge = TRUE', code = {
	## extract row names
	x_names <- row.names(ATOM)

	## calculate indicator
	indicator <- MIDPOINT(ATOM, na.bridge = TRUE)

	testthat::expect_equal(
		object = x_names,
		expected = rownames(indicator)
	)
})

## check that the length of the input
## matches the output length
##
## <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame>', code = {
	testthat::expect_equal(
		object = nrow(MIDPOINT(
			BTC
		)),
		expected = nrow(BTC)
	)
})

## check that the rownames are being
## respected for <data.frame>
testthat::test_that(desc = 'Row names are respected for <data.frame>', code = {
	## extract row names
	x_names <- row.names(BTC)

	## calculate indicator
	indicator <- MIDPOINT(BTC)

	testthat::expect_equal(
		object = x_names,
		expected = rownames(indicator)
	)
})

## <matrix> object
testthat::test_that(desc = 'Equal length of input and output for <matrix>', code = {
	testthat::expect_equal(
		object = nrow(MIDPOINT(
			SPY
		)),
		expected = nrow(SPY)
	)
})

## check that the rownames are being
## respected for <matrix>
testthat::test_that(desc = 'Row names are respected for <matrix>', code = {
	## extract row names
	## NOTE: by default the SPY has no
	##       rownames
	rownames(SPY) <- paste0("row", 1:nrow(SPY))

	## calculate indicator
	indicator <- MIDPOINT(SPY)

	testthat::expect_equal(
		object = paste0("row", 1:nrow(SPY)),
		expected = rownames(indicator)
	)
})

## check that <numeric> methods runs without
## issues and returns proper lengths
testthat::test_that(desc = '<numeric> methods', code = {
	## check that the <numeric> method
	## runs
	x <- testthat::expect_no_condition(
		MIDPOINT(BTC[[1]])
	)

	target_length <- length(BTC[[1]])

	if (NCOL(x) == 1L) {
		testthat::expect_true(is.double(x) || is.integer(x))
		testthat::expect_false(is.matrix(x))
		testthat::expect_equal(length(x), target_length)
	} else {
		testthat::expect_true(is.matrix(x))
		testthat::expect_equal(nrow(x), target_length)
	}
})
