## autogenerated unit-test
## from tools/generate_unit-tests.sh
## the file will be overwritten in the next iteration
##
## author: Serkan Korkmaz

## 1) test that it works
testthat::test_that(desc = 'description', code = {
	## 1) test that the alias and
	##    function returns the same values
	output <- testthat::expect_no_error(
		{
			rolling_min(
				x = SPY[[1]]
			)
		}
	)
})

## 5) check that the lenght of the input
##    matches the output length
##
## 5.1) <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame>', code = {
	testthat::expect_equal(
		object = length(rolling_min(
			BTC[[1]]
		)),
		expected = nrow(BTC)
	)
})
