## generate indicators
## from
generate_indicator <- function(
	family,
	title,
	fun,
	signature,
	default_formula,
	alias
) {
	system2(
		command = "bash",
		args = c(
			"tools/generate_indicator.sh",
			paste0("'", "indicator_template.R", "'"),
			paste0("'", family, "'"),
			paste0("'", title, "'"),
			paste0("'", fun, "'"),
			paste0("'", signature, "'"),
			paste0("'", default_formula, "'"),
			paste0("'", alias, "'")
		)
	)
}


DT <- data.table::data.table(
	family = 'Momentum Indicator',
	title = c(
		'Aroon',
		'Aroon Oscillator',
		'Chande Momentum Oscillator',
		'Commodity Channel Index',
		'Fast Stochastic',
		'Money Flow Index',
		'Moving Average Convergence Divergence',
		'Moving Average Convergence Divergence (Extended)',
		'Moving Average Convergence Divergence (Fixed)',
		'Relative Strength Index',
		'Stochastic',
		'Stochastic Relative Strength Index',
		'Ultimate Oscillator',
		'Average Directional Movement Index',
		'Average Directional Movement Index Rating',
		'Balance of Power',
		'Momentum',
		'Williams %R',
		'Percentage Price Oscillator',
		'Triple Exponential Average',
		'Directional Movement Index',
		'Intraday Movement Index',
		'Minus Directional Indicator',
		'Minus Directional Movement',
		'Plus Directional Indicator',
		'Plus Directional Movement',
		'Rate of Change',
		'Ratio of Change'
	),
	fun = c(
		'aroon',
		'aroon_oscillator',
		'chande_momentum_oscillator',
		'commodity_channel_index',
		'fast_stochastic',
		'money_flow_index',
		'moving_average_convergence_divergence',
		'extended_moving_average_convergence_divergence',
		'fixed_moving_average_convergence_divergence',
		'relative_strength_index',
		'stochastic',
		'stochastic_relative_strength_index',
		'ultimate_oscillator',
		'average_directional_movement_index',
		'average_direcitonal_movement_index_rating',
		'balance_of_power',
		'momentum',
		'williams_oscillator',
		'percentage_price_oscillator',
		'triple_exponential_average',
		'directional_movement_index',
		'intraday_movement_index',
		'minus_directional_indicator',
		'minus_directional_movement',
		'plus_directional_indicator',
		'plus_directional_movement',
		'rate_of_change',
		'ratio_of_change'
	),
	alias = c(
		'AROON',
		'AROONOSC',
		'CMO',
		'CCI',
		'STOCHF',
		'MFI',
		'MACD',
		'MACDEXT',
		'MACDFIX',
		'RSI',
		'STOCH',
		'STOCHRSI',
		'ULTOSC',
		'ADX',
		'ADXR',
		'BOP',
		'MOM',
		'WILLR',
		'PPO',
		'TRIX',
		'DX',
		'IMI',
		'MDI',
		'MDM',
		'PDI',
		'PDM',
		'ROC',
		'ROCR'
	),
	default_formula = c(
		'~ high + low',
		'~ high + low',
		'~ close',
		' ~ high + low + close',
		'~ high + low + close',
		'~ high + low + close + volume',
		'~close',
		'~close',
		'~close',
		'~close',
		'~ high + low + close',
		'~ high + low + close',
		'~ high + low + close',
		'~ high + low + close',
		'~ high + low + close',
		'~ open + high + low + close',
		'~ close',
		'~ high + low + close',
		'~close',
		'~close',
		'~high + low + close',
		'~open + close',
		'~high + low + close',
		'~high + low',
		'~high + low + close',
		'~high + low',
		'~close',
		'~close'
	),
	signature = c(
		'n=10',
		'n=10',
		'n=10',
		'n=10',
		'fastk=5,fastd=SMA(n=10)',
		'n = 10',
		'fast = 12,slow = 26,signal = 9',
		'fast = EMA(n = 12),slow = EMA(n = 26),signal = EMA(n = 9)',
		'signal = 9',
		'n=10',
		'fastk = 5,
	slowk = SMA(n = 10),
	slowd = SMA(n = 8)',
		'n=10,n_rsi=10,fastk=5,fastd=SMA(n=10)',
		'n=c(7, 14, 28)',
		'n=10',
		'n=10',
		'',
		'n=10',
		'n=10',
		'fast=7,slow=14,ma=SMA(n=10)',
		'n=10',
		'n=10',
		'n=10',
		'n=10',
		'n=10',
		'n=10',
		'n=10',
		'n=10',
		'n=10'
	)
)

for (i in 1:nrow(DT)) {
	generate_indicator(
		family = DT$family[i],
		title = DT$title[i],
		fun = DT$fun[i],
		signature = DT$signature[i],
		default_formula = DT$default_formula[i],
		alias = DT$alias[i]
	)
}
