DT <- data.table::data.table(
	title = c(
		# 58
		'Abandoned Baby',
		'Advance Block',
		'Belt Hold',
		'Break Away',
		'Closing Marubozu',
		'Concealing Baby Swallow',
		'Counter Attack',
		'Dark Cloud Cover',
		'Doji',
		'Doji Star',
		'Dragonfly Doji',
		'Engulfing',
		'Evening Doji Star',
		'Up/Down-gap side-by-side white lines',
		'Gravestone Doji',
		'Hammer',
		'Hanging Man',
		'Harami',
		'Harami Cross',
		'High Wave',
		'Hikkake',
		'Hikkake Modified',
		'Homing Pigeon',
		'In Neck',
		'Inverted Hammer',
		'Kicking',
		'Kicking Baby Length',
		'Long Legged Doji',
		'Long Line',
		'Marubozu',
		'Mat Hold',
		'Matching Low',
		'Morning Doji Star',
		'Morning Star',
		'On-Neck',
		'Piercing',
		'Rickshaw Man',
		'Rising/Falling Three Methods',
		'Separating Lines',
		'Shooting Star',
		'Short Line Candle',
		'Spinning Top',
		'Stalled Pattern',
		'Stick Sandwich',
		'Takuri',
		'Tasuki Gap',
		'Three Black Crows',
		'Identical Three Crows',
		'Three Inside',
		'Three-Line Strike',
		'Three Outside',
		'Three Stars in the South',
		'Three White Soldiers',
		'Thrusting',
		'Tristar',
		'Two Crows',
		'Unique Three River',
		'Upside Gap Two Crows',
		'Upside/Downside Gap Three Methods',
		'Ladder Bottom',
		'Evening Star'
	),
	fun = c(
		# 58
		'abandoned_baby',
		'advance_block',
		'belt_hold',
		'break_away',
		'closing_marubozu',
		'concealing_baby_swallow',
		'counter_attack',
		'dark_cloud_cover',
		'doji',
		'doji_star',
		'dragonfly_doji',
		'engulfing',
		'evening_doji_star',
		'gaps_side_white',
		'gravestone_doji',
		'hammer',
		'hanging_man',
		'harami',
		'harami_cross',
		'high_wave',
		'hikakke',
		'hikakke_mod',
		'homing_pigeon',
		'in_neck',
		'inverted_hammer',
		'kicking',
		'kicking_baby_length',
		'long_legged_doji',
		'long_line',
		'marubozu',
		'mat_hold',
		'matching_low',
		'morning_doji_star',
		'morning_star',
		'on_neck',
		'piercing',
		'rickshaw_man',
		'rise_fall_3_methods',
		'separating_lines',
		'shooting_star',
		'short_line',
		'spinning_top',
		'stalled_pattern',
		'stick_sandwich',
		'takuri',
		'tasuki_gap',
		'three_black_crows',
		'three_identical_crows',
		'three_inside',
		'three_line_strike',
		'three_outside',
		'three_stars_in_the_south',
		'three_white_soldiers',
		'thrusting',
		'tristar',
		'two_crows',
		'unique_3_river',
		'upside_gap_2_crows',
		'xside_gap_3_methods',
		'ladder_bottom',
		'evening_star'
	),
	signature = c(
		# 57
		'eps=0',
		'',
		'',
		'',
		'',
		'',
		'',
		'eps=0',
		'',
		'',
		'',
		'',
		'eps=0',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'eps=0',
		'',
		'eps=0',
		'eps=0',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'',
		'eps=0'
	),
	alias = c(
		# 58
		'CDLABANDONEDBABY',
		'CDLADVANCEBLOCK',
		'CDLBELTHOLD',
		'CDLBREAKAWAY',
		'CDLCLOSINGMARUBOZU',
		'CDLCONCEALBABYSWALL',
		'CDLCOUNTERATTACK',
		'CDLDARKCLOUDCOVER',
		'CDLDOJI',
		'CDLDOJISTAR',
		'CDLDRAGONFLYDOJI',
		'CDLENGULFING',
		'CDLEVENINGDOJISTAR',
		'CDLGAPSIDESIDEWHITE',
		'CDLGRAVESTONEDOJI',
		'CDLHAMMER',
		'CDLHANGINGMAN',
		'CDLHARAMI',
		'CDLHARAMICROSS',
		'CDLHIGHWAVE',
		'CDLHIKKAKE',
		'CDLHIKKAKEMOD',
		'CDLHOMINGPIGEON',
		'CDLINNECK',
		'CDLINVERTEDHAMMER',
		'CDLKICKING',
		'CDLKICKINGBYLENGTH',
		'CDLLONGLEGGEDDOJI',
		'CDLLONGLINE',
		'CDLMARUBOZU',
		'CDLMATHOLD',
		'CDLMATCHINGLOW',
		'CDLMORNINGDOJISTAR',
		'CDLMORNINGSTAR',
		'CDLONNECK',
		'CDLPIERCING',
		'CDLRICKSHAWMAN',
		'CDLRISEFALL3METHODS',
		'CDLSEPARATINGLINES',
		'CDLSHOOTINGSTAR',
		'CDLSHORTLINE',
		'CDLSPINNINGTOP',
		'CDLSTALLEDPATTERN',
		'CDLSTICKSANDWICH',
		'CDLTAKURI',
		'CDLTASUKIGAP',
		'CDL3BLACKCROWS',
		'CDLIDENTICAL3CROWS',
		'CDL3INSIDE',
		'CDL3LINESTRIKE',
		'CDL3OUTSIDE',
		'CDL3STARSINSOUTH',
		'CDL3WHITESOLDIERS',
		'CDLTHRUSTING',
		'CDLTRISTAR',
		'CDL2CROWS',
		'CDLUNIQUE3RIVER',
		'CDLUPSIDEGAP2CROWS',
		'CDLXSIDEGAP3METHODS',
		'CDLLADDERBOTTOM',
		'CDLEVENINGSTAR'
	),
	agnostic = c(
		# 57
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'TRUE',
		'FALSE',
		'FALSE',
		'FALSE',
		'TRUE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'TRUE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'TRUE',
		'TRUE',
		'TRUE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'TRUE',
		'FALSE',
		'FALSE',
		'FALSE',
		'TRUE',
		'TRUE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE',
		'FALSE'
	)
)


generate_indicator <- function(
	title,
	fun,
	signature,
	default_formula,
	alias
) {
	system2(
		command = "bash",
		args = c(
			"tools/generate_indicator.sh",
			'candlestick_template.R',
			's',
			paste0("'", title, "'"),
			paste0("'", fun, "'"),
			paste0("'", signature, "'"),
			paste0("'", default_formula, "'"),
			paste0("'", alias, "'")
		)
	)
}


for (i in 1:nrow(DT)) {
	generate_indicator(
		title = DT$title[i],
		fun = DT$fun[i],
		signature = DT$signature[i],
		default_formula = DT$agnostic[i],
		alias = DT$alias[i]
	)
}
