#!/usr/bin/env bash

## 1) generate unit-test
Rscript -e "usethis::use_test('$1')"

## 2) populate test file
##    with standard stuff
cat > tests/testthat/test-ta_$1.R <<EOF

## autogenerated unit-test
## from tools/generate_unit-tests.sh
## the file will be overwritten in the next iteration
## 
## author: Serkan Korkmaz
## updated: $(date +"%Y-%m-%d")

## 1) alias and function similarity
##    checks
testthat::test_that(desc = 'Alias and function similarity', code = {
    ## 1) test that the alias and 
    ##    function returns the same values
    output <- $1(SPY)
    alias  <- $2(SPY)

    ## 1.1) check if the values
	##      are equal
	testthat::expect_equal(
		object   = output,
		expected = alias
	)
})

## 2) {plotly}-method for data.frames
##    and matrices
## 
## 2.1) data.frame
testthat::test_that(desc = '{plotly}-methods for <data.frame> and <matrix>', code = {
    ## 2) test that charting
	##    works
	output <- testthat::expect_no_error(
		{
			chart(BTC)
			indicator($1)
		}
	)

	## 2.1) test that it outputs
	##      a plotly object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})

## 2.2) matrix
testthat::test_that(desc = '{plotly}-methods for <data.frame> and <matrix>', code = {
    ## 2) test that charting
	##    works
	output <- testthat::expect_no_error(
		{
			chart(SPY)
			indicator($1)
		}
	)

	## 2.1) test that it outputs
	##      a plotly object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})

## 3) class-in, class-out
##    for matrices
testthat::test_that(desc = 'Class in, class out (<matrix>)', code = {
    ## 3.1) matrix
	testthat::expect_true(
		inherits($1(SPY), class(SPY))
	)

})

## 3) class-in, class-out
##    for data.frame
testthat::test_that(desc = 'Class in, class out (<data.frame>)', code = {
    

	## 3.2) data.frame
	testthat::expect_true(
		inherits($1(BTC), class(BTC))
	)
})

## 4) check default calls vs expected
##    calls
testthat::test_that(desc = 'Class in, class out', code = {
    testthat::expect_equal(
		object = $1(
			BTC
		),
		expected = $1(
			BTC,
			cols = $3
		)
	)
})

EOF