#!/usr/bin/env bash
set -euo pipefail

## 1) environment variables
##    to determine unit-tests
FUN=${FUN:?}
TA_FUN=${TA_FUN:?}
ALIAS=${ALIAS:-$TA_FUN}
FORMULA=${FORMULA:-"~close"}
PLOTLY=${PLOTLY:-0}
NUMERIC=${NUMERIC:-1}
OUTPUTFILE=${OUTPUTFILE:-"tests/testthat/test-ta_${TA_FUN}.R"}
ROLLING=${ROLLING:-0}

## 2) fast-track exiting of the
##    program for rolling statistics
if [[ $ROLLING -eq 1 ]]; then

## 2.2) check if the signature includes
##      a 'y' and set it to SPY[[2]]
ADDITIONAL=''
  for a in "$@"; do
    case "$a" in
      y|y=*) ADDITIONAL=',y=SPY[[2]]'; break ;;
    esac
done

cat > ${OUTPUTFILE} << EOF
## autogenerated unit-test
## from tools/generate_unit-tests.sh
## the file will be overwritten in the next iteration
## 
## author: Serkan Korkmaz

## 1) test that it works
testthat::test_that(desc = 'description', code = {

    ## 1) test that the alias and 
    ##    function returns the same values
    output <- testthat::expect_no_error(
		{
			${FUN}(
				x = SPY[[1]]${ADDITIONAL}
			)	
		}
	)
})

## 5) check that the lenght of the input
##    matches the output length
##
## 5.1) <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame>', code = {
    testthat::expect_equal(
		object = length(${FUN}(
			BTC[[1]]${ADDITIONAL}
		)),
		expected = nrow(BTC)
	)
})

EOF

exit 1;
fi

## 1) populate test file
##    with standard stuff
cat > ${OUTPUTFILE} <<EOF
## autogenerated unit-test
## from tools/generate_unit-tests.sh
## the file will be overwritten in the next iteration
## 
## author: Serkan Korkmaz

## 1) alias and function similarity
##    checks this ensures that 
##    ${FUN} and ${ALIAS} produces the same results
testthat::test_that(desc = 'Alias and function similarity', code = {

    ## 1) test that the alias and 
    ##    function returns the same values
    output <- ${FUN}(SPY)
    alias  <- ${ALIAS}(SPY)

    ## 1.1) check if the values
	##      are equal
	testthat::expect_equal(
		object   = output,
		expected = alias
	)

})

## 3) type-checks for data.frames and
##    matrices
##
## 3.1) <matrix> object
testthat::test_that(desc = 'Class in, class out (<matrix>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(${FUN}(SPY), class(SPY))
	)

})

## 3.2) <data.frame> object
testthat::test_that(desc = 'Class in, class out (<data.frame>)', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_true(
		inherits(${FUN}(BTC), class(BTC))
	)
})

## 4) check that the default calls
##    matches that of the constructed call
##    with default values.
##
##    NOTE: This test is more of a test of the internal
##          series() function
testthat::test_that(desc = 'Default calls', code = {
    testthat::expect_equal(
		object = ${FUN}(
			BTC
		),
		expected = ${FUN}(
			BTC,
			cols = ${FORMULA}
		)
	)
})

## 5) check that the lenght of the input
##    matches the output length
##
## 5.1) <data.frame> object
testthat::test_that(desc = 'Equal length of input and output for <data.frame>', code = {
    testthat::expect_equal(
		object = nrow(${FUN}(
			BTC
		)),
		expected = nrow(BTC)
	)
})

## 5.2) <matrix> object
testthat::test_that(desc = 'Equal length of input and output for <matrix>', code = {
    testthat::expect_equal(
		object = nrow(${FUN}(
			SPY
		)),
		expected = nrow(SPY)
	)
})

EOF

## Add plotly methods
if [[ $PLOTLY -eq 1 ]]; then
	cat >> ${OUTPUTFILE} <<EOF

## 2) {plotly}-method checks for data.frames
##    and matrices
## 
## 2.1) data.frame checks
testthat::test_that(desc = '{plotly}-methods for <data.frame>', code = {
	## 1) check that ${FUN} can
	##    use {plotly} without any issues
	output <- testthat::expect_no_error(
		{
			chart(BTC)
			indicator(${FUN})
		}
	)

	## 1.1) check that the output
	##      is a {plotly}-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})

## 2.2) matrix checks
testthat::test_that(desc = '{plotly}-methods for <matrix>', code = {
	## 1) check that ${FUN} can
	##    use {plotly} without any issues
	output <- testthat::expect_no_error(
		{
			chart(SPY)
			indicator(${FUN})
		}
	)

	## 1.1) check that the output
	##      is a {plotly}-object
	testthat::expect_true(
		inherits(output, "plotly")
	)
})
EOF
fi


## Add plotly methods
if [[ $NUMERIC -eq 1 ]]; then
	cat >> ${OUTPUTFILE} <<EOF

testthat::test_that(desc = 'Numeric Methods', code = {
	## 1) check that the output class
	##    matches the input class
	testthat::expect_no_error(
		${FUN}(BTC[[1]])
	)
})
EOF
fi