// Generated from tools/generate_API.sh
#ifndef _API_H_
#define _API_H_

#include <Rinternals.h>

// clang-format off
SEXP impl_ta_ACCBANDS(SEXP inHigh, SEXP inLow, SEXP inClose, SEXP optTimePeriod);
SEXP impl_ta_ADOSC(SEXP inHigh, SEXP inLow, SEXP inClose, SEXP inVolume, SEXP optFastPeriod, SEXP optSlowPeriod);
SEXP impl_ta_AD(SEXP inHigh, SEXP inLow, SEXP inClose, SEXP inVolume);
SEXP impl_ta_ADXR(SEXP high, SEXP low, SEXP close, SEXP optTimePeriod);
SEXP impl_ta_ADX(SEXP high, SEXP low, SEXP close, SEXP optTimePeriod);
SEXP impl_ta_APO(SEXP x_input, SEXP fast_period, SEXP slow_period, SEXP ma_type);
SEXP impl_ta_AROONOSC(SEXP high, SEXP low, SEXP timeperiod);
SEXP impl_ta_AROON(SEXP high, SEXP low, SEXP timeperiod);
SEXP impl_ta_BBANDS(SEXP inReal, SEXP optTimePeriod, SEXP optNbDevUp, SEXP optNbDevDn, SEXP optMAType);
SEXP impl_ta_BOP(SEXP open, SEXP high, SEXP low, SEXP close);
SEXP impl_ta_CCI(SEXP high, SEXP low, SEXP close, SEXP optTimePeriod);
SEXP impl_ta_CDL2CROWS(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDL3BLACKCROWS(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDL3INSIDE(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDL3LINESTRIKE(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDL3OUTSIDE(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDL3STARSINSOUTH(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDL3WHITESOLDIERS(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLABANDONEDBABY(SEXP open, SEXP high, SEXP low, SEXP close, SEXP penetration, SEXP normalize_flag);
SEXP impl_ta_CDLADVANCEBLOCK(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLBELTHOLD(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLBREAKAWAY(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLCLOSINGMARUBOZU(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLCONCEALBABYSWALL(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLCOUNTERATTACK(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLDARKCLOUDCOVER(SEXP open, SEXP high, SEXP low, SEXP close, SEXP penetration, SEXP normalize_flag);
SEXP impl_ta_CDLDOJI(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLDOJISTAR(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLDRAGONFLYDOJI(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLENGULFING(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLEVENINGDOJISTAR(SEXP open, SEXP high, SEXP low, SEXP close, SEXP penetration, SEXP normalize_flag);
SEXP impl_ta_CDLGAPSIDESIDEWHITE(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLGRAVESTONEDOJI(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLHAMMER(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLHANGINGMAN(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLHARAMICROSS(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLHARAMI(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLHIGHWAVE(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLHIKKAKEMOD(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLHIKKAKE(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLHOMINGPIGEON(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLIDENTICAL3CROWS(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLINNECK(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLINVERTEDHAMMER(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLKICKINGBYLENGTH(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLKICKING(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLLONGLEGGEDDOJI(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLLONGLINE(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLMARUBOZU(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLMATCHINGLOW(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLMATHOLD(SEXP open, SEXP high, SEXP low, SEXP close, SEXP penetration, SEXP normalize_flag);
SEXP impl_ta_CDLMORNINGDOJISTAR(SEXP open, SEXP high, SEXP low, SEXP close, SEXP penetration, SEXP normalize_flag);
SEXP impl_ta_CDLMORNINGSTAR(SEXP open, SEXP high, SEXP low, SEXP close, SEXP penetration, SEXP normalize_flag);
SEXP impl_ta_CDLONNECK(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLPIERCING(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLRICKSHAWMAN(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLRISEFALL3METHODS(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLSEPARATINGLINES(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLSHOOTINGSTAR(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLSHORTLINE(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLSPINNINGTOP(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLSTALLEDPATTERN(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLSTICKSANDWICH(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLTAKURI(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLTASUKIGAP(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLTHRUSTING(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLTRISTAR(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLUNIQUE3RIVER(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLUPSIDEGAP2CROWS(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CDLXSIDEGAP3METHODS(SEXP open, SEXP high, SEXP low, SEXP close, SEXP normalize_flag);
SEXP impl_ta_CMO(SEXP x, SEXP optTimePeriod);
SEXP impl_ta_DX(SEXP high, SEXP low, SEXP close, SEXP timeperiod);
SEXP impl_ta_HT_DCPERIOD(SEXP inReal);
SEXP impl_ta_HT_DCPHASE(SEXP inReal);
SEXP impl_ta_HT_PHASOR(SEXP inReal);
SEXP impl_ta_HT_SINE(SEXP inReal);
SEXP impl_ta_HT_TRENDLINE(SEXP inReal);
SEXP impl_ta_HT_TRENDMODE(SEXP inReal);
SEXP impl_ta_IMI(SEXP open, SEXP close, SEXP timeperiod);
SEXP impl_ta_MACDEXT(SEXP x, SEXP fast_period, SEXP fast_matype, SEXP slow_period, SEXP slow_matype, SEXP signal_period, SEXP signal_matype);
SEXP impl_ta_MACDFIX(SEXP inReal, SEXP optSignalPeriod);
SEXP impl_ta_MACD(SEXP x, SEXP optFastPeriod, SEXP optSlowPeriod, SEXP optSignalPeriod);
SEXP impl_ta_MA(SEXP x, SEXP period, SEXP matype);
SEXP impl_ta_MDI(SEXP high, SEXP low, SEXP close, SEXP timeperiod);
SEXP impl_ta_MDM(SEXP high, SEXP low, SEXP timeperiod);
SEXP impl_ta_MFI(SEXP high, SEXP low, SEXP close, SEXP volume, SEXP timeperiod);
SEXP impl_ta_MOM(SEXP real, SEXP timeperiod);
SEXP impl_ta_OBV(SEXP close, SEXP volume);
SEXP impl_ta_PDI(SEXP high, SEXP low, SEXP close, SEXP timeperiod);
SEXP impl_ta_PDM(SEXP high, SEXP low, SEXP timeperiod);
SEXP impl_ta_PPO(SEXP real, SEXP fastperiod, SEXP slowperiod, SEXP ma_type);
SEXP impl_ta_ROCR(SEXP in_real, SEXP timeperiod);
SEXP impl_ta_ROC(SEXP in_real, SEXP timeperiod);
SEXP impl_ta_RSI(SEXP inReal, SEXP optTimePeriod);
SEXP impl_ta_SAREXT(SEXP high, SEXP low, SEXP start_value, SEXP offset_on_reverse, SEXP accel_init_long, SEXP accel_long, SEXP accel_max_long, SEXP accel_init_short, SEXP accel_short, SEXP accel_max_short);
SEXP impl_ta_SAR(SEXP high, SEXP low, SEXP acceleration, SEXP maximum);
SEXP impl_ta_STOCHF(SEXP high, SEXP low, SEXP close, SEXP fastk_period, SEXP fastd_period, SEXP fastd_matype);
SEXP impl_ta_STOCHRSI(SEXP real, SEXP timeperiod, SEXP fastk_period, SEXP fastd_period, SEXP fastd_matype, SEXP offset_by_RSI);
SEXP impl_ta_STOCH(SEXP high, SEXP low, SEXP close, SEXP fastk_period, SEXP slowk_period, SEXP slowk_matype, SEXP slowd_period, SEXP slowd_matype);
SEXP impl_ta_TRIX(SEXP real, SEXP timeperiod);
SEXP impl_ta_ULTOSC(SEXP high, SEXP low, SEXP close, SEXP timeperiod1, SEXP timeperiod2, SEXP timeperiod3);
SEXP impl_ta_WILLR(SEXP high, SEXP low, SEXP close, SEXP timeperiod);
SEXP initialize_ta_lib();
SEXP shutdown_ta_lib();
// clang-format on

#endif //_API_H
