// Generated from tools/generate_FFI.sh
#include <R.h>
#include <R_ext/Rdynload.h>
#include <Rinternals.h>
#include <stdlib.h>

#include "api.h"

// clang-format off
#define CALLDEF(name, n) {#name, (DL_FUNC) &name, n}
// clang-format on

static const R_CallMethodDef CallEntries[] = {
  CALLDEF(impl_ta_ACCBANDS, 4),
  CALLDEF(impl_ta_ADOSC, 6),
  CALLDEF(impl_ta_AD, 4),
  CALLDEF(impl_ta_ADXR, 4),
  CALLDEF(impl_ta_ADX, 4),
  CALLDEF(impl_ta_APO, 4),
  CALLDEF(impl_ta_AROONOSC, 3),
  CALLDEF(impl_ta_AROON, 3),
  CALLDEF(impl_ta_ATR, 4),
  CALLDEF(impl_ta_BBANDS, 5),
  CALLDEF(impl_ta_BOP, 4),
  CALLDEF(impl_ta_CCI, 4),
  CALLDEF(impl_ta_CDL2CROWS, 5),
  CALLDEF(impl_ta_CDL3BLACKCROWS, 5),
  CALLDEF(impl_ta_CDL3INSIDE, 5),
  CALLDEF(impl_ta_CDL3LINESTRIKE, 5),
  CALLDEF(impl_ta_CDL3OUTSIDE, 5),
  CALLDEF(impl_ta_CDL3STARSINSOUTH, 5),
  CALLDEF(impl_ta_CDL3WHITESOLDIERS, 5),
  CALLDEF(impl_ta_CDLABANDONEDBABY, 6),
  CALLDEF(impl_ta_CDLADVANCEBLOCK, 5),
  CALLDEF(impl_ta_CDLBELTHOLD, 5),
  CALLDEF(impl_ta_CDLBREAKAWAY, 5),
  CALLDEF(impl_ta_CDLCLOSINGMARUBOZU, 5),
  CALLDEF(impl_ta_CDLCONCEALBABYSWALL, 5),
  CALLDEF(impl_ta_CDLCOUNTERATTACK, 5),
  CALLDEF(impl_ta_CDLDARKCLOUDCOVER, 6),
  CALLDEF(impl_ta_CDLDOJI, 5),
  CALLDEF(impl_ta_CDLDOJISTAR, 5),
  CALLDEF(impl_ta_CDLDRAGONFLYDOJI, 5),
  CALLDEF(impl_ta_CDLENGULFING, 5),
  CALLDEF(impl_ta_CDLEVENINGDOJISTAR, 6),
  CALLDEF(impl_ta_CDLEVENINGSTAR, 6),
  CALLDEF(impl_ta_CDLGAPSIDESIDEWHITE, 5),
  CALLDEF(impl_ta_CDLGRAVESTONEDOJI, 5),
  CALLDEF(impl_ta_CDLHAMMER, 5),
  CALLDEF(impl_ta_CDLHANGINGMAN, 5),
  CALLDEF(impl_ta_CDLHARAMICROSS, 5),
  CALLDEF(impl_ta_CDLHARAMI, 5),
  CALLDEF(impl_ta_CDLHIGHWAVE, 5),
  CALLDEF(impl_ta_CDLHIKKAKEMOD, 5),
  CALLDEF(impl_ta_CDLHIKKAKE, 5),
  CALLDEF(impl_ta_CDLHOMINGPIGEON, 5),
  CALLDEF(impl_ta_CDLIDENTICAL3CROWS, 5),
  CALLDEF(impl_ta_CDLINNECK, 5),
  CALLDEF(impl_ta_CDLINVERTEDHAMMER, 5),
  CALLDEF(impl_ta_CDLKICKINGBYLENGTH, 5),
  CALLDEF(impl_ta_CDLKICKING, 5),
  CALLDEF(impl_ta_CDLLADDERBOTTOM, 5),
  CALLDEF(impl_ta_CDLLONGLEGGEDDOJI, 5),
  CALLDEF(impl_ta_CDLLONGLINE, 5),
  CALLDEF(impl_ta_CDLMARUBOZU, 5),
  CALLDEF(impl_ta_CDLMATCHINGLOW, 5),
  CALLDEF(impl_ta_CDLMATHOLD, 6),
  CALLDEF(impl_ta_CDLMORNINGDOJISTAR, 6),
  CALLDEF(impl_ta_CDLMORNINGSTAR, 6),
  CALLDEF(impl_ta_CDLONNECK, 5),
  CALLDEF(impl_ta_CDLPIERCING, 5),
  CALLDEF(impl_ta_CDLRICKSHAWMAN, 5),
  CALLDEF(impl_ta_CDLRISEFALL3METHODS, 5),
  CALLDEF(impl_ta_CDLSEPARATINGLINES, 5),
  CALLDEF(impl_ta_CDLSHOOTINGSTAR, 5),
  CALLDEF(impl_ta_CDLSHORTLINE, 5),
  CALLDEF(impl_ta_CDLSPINNINGTOP, 5),
  CALLDEF(impl_ta_CDLSTALLEDPATTERN, 5),
  CALLDEF(impl_ta_CDLSTICKSANDWICH, 5),
  CALLDEF(impl_ta_CDLTAKURI, 5),
  CALLDEF(impl_ta_CDLTASUKIGAP, 5),
  CALLDEF(impl_ta_CDLTHRUSTING, 5),
  CALLDEF(impl_ta_CDLTRISTAR, 5),
  CALLDEF(impl_ta_CDLUNIQUE3RIVER, 5),
  CALLDEF(impl_ta_CDLUPSIDEGAP2CROWS, 5),
  CALLDEF(impl_ta_CDLXSIDEGAP3METHODS, 5),
  CALLDEF(impl_ta_CMO, 2),
  CALLDEF(impl_ta_DX, 4),
  CALLDEF(impl_ta_HT_DCPERIOD, 1),
  CALLDEF(impl_ta_HT_DCPHASE, 1),
  CALLDEF(impl_ta_HT_PHASOR, 1),
  CALLDEF(impl_ta_HT_SINE, 1),
  CALLDEF(impl_ta_HT_TRENDLINE, 1),
  CALLDEF(impl_ta_HT_TRENDMODE, 1),
  CALLDEF(impl_ta_IMI, 3),
  CALLDEF(impl_ta_MACDEXT, 7),
  CALLDEF(impl_ta_MACDFIX, 2),
  CALLDEF(impl_ta_MACD, 4),
  CALLDEF(impl_ta_MA, 3),
  CALLDEF(impl_ta_MFI, 5),
  CALLDEF(impl_ta_MINUS_DI, 4),
  CALLDEF(impl_ta_MINUS_DM, 3),
  CALLDEF(impl_ta_MOM, 2),
  CALLDEF(impl_ta_NATR, 4),
  CALLDEF(impl_ta_OBV, 2),
  CALLDEF(impl_ta_PLUS_DI, 4),
  CALLDEF(impl_ta_PLUS_DM, 3),
  CALLDEF(impl_ta_PPO, 4),
  CALLDEF(impl_ta_ROCR, 2),
  CALLDEF(impl_ta_ROC, 2),
  CALLDEF(impl_ta_RSI, 2),
  CALLDEF(impl_ta_SAREXT, 10),
  CALLDEF(impl_ta_SAR, 4),
  CALLDEF(impl_ta_STOCHF, 6),
  CALLDEF(impl_ta_STOCHRSI, 6),
  CALLDEF(impl_ta_STOCH, 8),
  CALLDEF(impl_ta_TRANGE, 3),
  CALLDEF(impl_ta_TRIX, 2),
  CALLDEF(impl_ta_ULTOSC, 6),
  CALLDEF(impl_ta_WILLR, 4),
  CALLDEF(initialize_ta_lib, 0),
  CALLDEF(reset_candle_setting, 0),
  CALLDEF(set_candle_setting, 4),
  CALLDEF(shutdown_ta_lib, 0),
  {NULL, NULL, 0}};

void R_init_talib(DllInfo *dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
