// Trading Volume
//
// Description:
//  Trading volume is not an officially exported TA-Lib indicator, so this
//  wrapper is hand-written instead of being generated by the TA_WRAPPER
//  X-macro in wrapper.h. It returns the volume series alongside one moving
//  average column per 'ma' specification.
//
// Parameters
//   inReal     REALSXP  the volume series
//   maSpec     VECSXP   list of integer(2) specs: c(period, maType); may be
//   NULL na_bridge  LGLSXP   drop NA rows, compute on the dense series, scatter
//   back
//
// Returns
//   REALSXP matrix (n x (1 + length(maSpec))) with columns:
//     "VOLUME", "<MAType><period>" e.g. "SMA7"
//
//   The "lookback" attribute is the (normalized) maximum lookback across all
//   maSpec entries; the "VOLUME" column itself always has a lookback of 0.
//
#include "NA-handling.h"
#include "attributes.h"
#include "names.h"
#include "shift.h"
#include "talib_utils.h"
#include <R_ext/RS.h>
#include <Rinternals.h>
#include <limits.h>
#include <stdio.h>
#include <string.h>

// MAType names mapped by indices
// clang-format off
static const char *const MATypeNames[] = {
  "SMA", 
  "EMA",
  "WMA", 
  "DEMA", 
  "TEMA",
  "TRIMA",
  "KAMA",
  "MAMA",
  "T3"
};
// clang-format on

// Trading Volume lookback
// clang-format off
SEXP impl_ta_VOLUME_lookback(
    SEXP maSpec
)
// clang-format on
{

  const int n_ma = Rf_isNull(maSpec) ? 0 : LENGTH(maSpec);
  int lookback = 0;

  if (n_ma > 0) {

    for (int j = 0; j < n_ma; ++j) {
      // each specification is integer(2): c(period, maType)
      const int *spec = INTEGER(VECTOR_ELT(maSpec, j));
      const int ma_lookback = TA_MA_Lookback(spec[0], (TA_MAType)spec[1]);
      if (ma_lookback > lookback) {
        lookback = ma_lookback;
      }
    }
  } else {
    lookback += 1;
  }

  return Rf_ScalarInteger(normalize_lookback(lookback));
}

// clang-format off
SEXP impl_ta_VOLUME(
    SEXP inReal,
    SEXP maSpec,
    SEXP na_bridge
)
// clang-format on
{
  // protection counter
  int protection_counter = 0;

  // extract length of the
  // input vector
  R_xlen_t ta_n = XLENGTH(inReal);

  // throw error if the length
  // is larger than the allowed
  if (ta_n > INT_MAX) {
    Rf_error("TA_VOLUME: series length exceeds INT_MAX");
  }

  // clang-format off
  const double *volume = ta_real(
    inReal, 
    ta_n, 
    &protection_counter, 
    "inReal"
  );
  // clang-format on

  // get number of moving averages
  // with the number of columns
  //  NOTE: There is always one column (volume column)
  const int n_ma = Rf_isNull(maSpec) ? 0 : LENGTH(maSpec);
  const int n_cols = 1 + n_ma;

  // identify and extract missing values
  // from the input
  //
  // see NA-handling.h for more details
  int ta_bridge = (Rf_asLogical(na_bridge) == TRUE);
  R_xlen_t ta_calc = ta_n;
  unsigned char *ta_mask = NULL;
  if (ta_bridge && ta_n > 0) {

    const double *ta_ins[] = {volume};
    ta_calc = build_presence_mask(ta_ins, 1, ta_n, &ta_mask);
    if (ta_calc > 0) {
      double *ta_dense = dense_array(ta_calc, 1);
      volume = compact_array(ta_dense, volume, ta_mask, ta_n);
    }
  }

  // construct output matrix
  // and copy data
  SEXP out = PROTECT(Rf_allocMatrix(REALSXP, (int)ta_n, n_cols));
  protection_counter++;
  double *out_ptr = REAL(out);

  memcpy(out_ptr, volume, (size_t)ta_calc * sizeof(double));

  const char **colname =
    (const char **)R_alloc((size_t)n_cols, sizeof(*colname));
  colname[0] = "VOLUME";

  int lookback = 0;
  for (int j = 0; j < n_ma; ++j) {

    const int *spec = INTEGER(VECTOR_ELT(maSpec, j));
    const int period = spec[0];
    const TA_MAType ma_type = (TA_MAType)spec[1];

    // track the largest lookback seen so far
    const int ma_lookback = TA_MA_Lookback(period, ma_type);
    if (ma_lookback > lookback) {
      lookback = ma_lookback;
    }

    // moving average is written into column (j + 1)
    double *ma = out_ptr + (size_t)(j + 1) * (size_t)ta_n;

    int begIdx = 0;
    int nbElement = 0;
    if (ta_calc > 0) {
      // clang-format off
      TA_RetCode return_value = TA_MA(
        0,
        (int)ta_calc - 1,
        volume,
        period,
        ma_type,
        &begIdx,
        &nbElement,
        ma
      );
      // clang-format on
      ta_check(return_value, "TA_MA");
    }

    if (ta_bridge) {
      scatter_array(ma, ta_n, ta_mask, ta_calc, begIdx, nbElement);
    } else {
      shift_array(ma, ta_n, begIdx, nbElement);
    }

    char *buffer = (char *)R_alloc(32, sizeof(char));
    snprintf(buffer, 32, "%s%d", MATypeNames[ma_type], period);
    colname[j + 1] = buffer;
  }

  if (ta_bridge) {
    scatter_array(out_ptr, ta_n, ta_mask, ta_calc, 0, (int)ta_calc);
  }

  // set the column names and the (normalized, maximum) lookback attribute
  // see names.h and attributes.h for more details
  set_colnames(out, colname, n_cols);
  set_attribute(out, LOOKBACK, Rf_ScalarInteger(lookback), &protection_counter);

  UNPROTECT(protection_counter);
  return out;
}
