## tests/testthat/test-parity.R
##
## AUTO-GENERATED. Do not edit this file in tests/testthat/ - edit the
## source template at codegen/parity/test_parity_template.R instead.
## The Makefile copies this template into tests/testthat/test-parity.R
## before running `make test` / `make check` / `make parity`, and
## removes it again on `make clean` / `make purge`.
##
## What this checks:
##   For every .rds in $TALIB_PARITY_SNAPSHOT_DIR, resolve the matching
##   R wrapper via the package's alias convention (every TA-Lib name X
##   is exported as both x_long_name() and X()), invoke it WITH WRAPPER
##   DEFAULTS (no extra args), and compare each output column
##   positionally against the canonical upstream snapshot using
##   all.equal() with sqrt(.Machine$double.eps) tolerance.
##
## Test philosophy:
##   The snapshot reflects canonical TA-Lib behaviour with metadata
##   defaults (including the conventional input columns: close for
##   single-Real inputs, OHLCV per flags for Price inputs). The R
##   wrapper is invoked with its own defaults. Any divergence -
##   wrong default column, wrong default period, wrong default MAType,
##   missing output, etc. - shows up as a failed expectation.
##
##
## Skip behaviour:
##   - skip when TALIB_PARITY_SNAPSHOT_DIR is unset/missing (e.g. when
##     someone runs devtools::test() without first running `make parity`).

suppressPackageStartupMessages(library(talib))

## Force candlestick wrappers to emit raw -100/0/100 ints (the form
## upstream produces). Without this they divide by 100 and would never
## match the snapshot.
options(talib.normalize = FALSE)

.parity_snapshot_dir <- function() {
	d <- Sys.getenv("TALIB_PARITY_SNAPSHOT_DIR", unset = "")
	if (!nzchar(d)) {
		return(NULL)
	}
	if (!dir.exists(d)) {
		return(NULL)
	}
	d
}

## ---- Per-indicator overrides --------------------------------------------
##
## Each entry is one of:
##   - a function(btc, snap) returning the R wrapper's output
##   - a list(call = function(btc, snap), compare_cols = N) for partial
##     comparisons when a wrapper intentionally exposes a subset of
##     upstream's outputs
##
## What overrides DO and DON'T do:
##   DO bridge a signature mismatch (wrapper takes vector(s), not a
##      data.frame) - see the rolling-statistics family below
##   DO restrict comparison shape when the wrapper intentionally exposes a
##      subset of upstream's outputs
##   DON'T silently match the wrapper's actual behaviour to make the test
##      pass. If the wrapper has a real bug (wrong default column, wrong
##      MAType, etc.), the test should fail and surface it.
R_CALL_OVERRIDES <- list(
	## --- Signature bridges (wrapper takes vector inputs, not a data.frame) ---
	## Inputs match the canonical snapshot wiring in parity_gen.c
	## (high+low for the 2-Real convention; close for single-Real).
	## NO period forwarding: wrapper defaults are tested against canonical.
	CORREL = function(btc, snap) talib::CORREL(btc$high, btc$low),
	BETA = function(btc, snap) talib::BETA(btc$high, btc$low),
	VAR = function(btc, snap) talib::VAR(btc$close),
	STDDEV = function(btc, snap) talib::STDDEV(btc$close),
	MAX = function(btc, snap) talib::MAX(btc$close),
	MIN = function(btc, snap) talib::MIN(btc$close),
	SUM = function(btc, snap) talib::SUM(btc$close)
)

## Invoke the R wrapper for an indicator. Returns a list:
##   result       - the raw output (matrix / data.frame / NULL)
##   compare_cols - NULL to compare all columns (default), or an integer
##                  N to restrict comparison to the first N columns
call_r_wrapper <- function(name, btc, snap) {
	override <- R_CALL_OVERRIDES[[name]]
	if (is.function(override)) {
		return(list(result = override(btc, snap), compare_cols = NULL))
	}
	if (is.list(override)) {
		return(list(
			result = override$call(btc, snap),
			compare_cols = override$compare_cols
		))
	}
	## Default: call with no args. Wrapper's own defaults drive the test.
	## Anything that diverges from canonical (default column choice,
	## default MAType, default period, default formula) shows up as a
	## failed expectation downstream.
	fn <- get(name, envir = asNamespace("talib"), inherits = FALSE)
	list(result = fn(btc), compare_cols = NULL)
}

## ---- Test enumeration ---------------------------------------------------

.parity_run <- function() {
	snapshot_dir <- .parity_snapshot_dir()
	if (is.null(snapshot_dir)) {
		test_that("parity: TA-Lib upstream snapshot present", {
			skip(paste0(
				"TALIB_PARITY_SNAPSHOT_DIR is unset or missing.\n",
				"Run `make parity` to generate the snapshot."
			))
		})
		return(invisible(NULL))
	}

	snap_files <- list.files(
		snapshot_dir,
		pattern = "\\.rds$",
		full.names = TRUE
	)
	if (length(snap_files) == 0L) {
		test_that("parity: TA-Lib upstream snapshot present", {
			skip(paste0("No .rds files in ", snapshot_dir))
		})
		return(invisible(NULL))
	}

	tol <- sqrt(.Machine$double.eps)

	for (snap_file in snap_files) {
		snap <- readRDS(snap_file)
		name <- snap$upstream

		test_that(paste0("parity: ", name), {
			expect_true(
				exists(name, envir = asNamespace("talib"), inherits = FALSE),
				info = paste0(
					"R wrapper '",
					name,
					"' must be exported by talib"
				)
			)

			called <- call_r_wrapper(name, BTC, snap)
			result <- called$result

			mat <- if (is.matrix(result)) {
				result
			} else if (is.data.frame(result)) {
				as.matrix(result)
			} else if (is.numeric(result)) {
				matrix(result, ncol = 1L)
			} else {
				fail(paste0(
					"unexpected result class for ",
					name,
					": ",
					paste(class(result), collapse = "/")
				))
				return(invisible(NULL))
			}

			## How many columns to compare. Default: all of upstream's.
			## Override: the wrapper intentionally exposes a subset
			## of upstream's outputs.
			n_expected <- if (is.null(called$compare_cols)) {
				length(snap$output_names)
			} else {
				as.integer(called$compare_cols)
			}

			expect_equal(
				nrow(mat),
				nrow(BTC),
				info = paste0(name, ": row count mismatch")
			)
			expect_equal(
				ncol(mat),
				n_expected,
				info = paste0(
					name,
					": R column count (",
					ncol(mat),
					") does not match expected (",
					n_expected,
					")"
				)
			)

			for (i in seq_len(n_expected)) {
				r_col <- as.double(mat[, i])
				ta_col <- as.double(snap$outputs[[i]])
				expect_equal(
					r_col,
					ta_col,
					tolerance = tol,
					info = paste0(
						name,
						" col ",
						i,
						" (",
						snap$output_names[i],
						")"
					)
				)
			}

			lb <- attr(result, "lookback")
			if (
				!is.null(lb) && !is.null(snap$lookback) && !is.na(snap$lookback)
			) {
				expect_equal(
					as.integer(lb),
					as.integer(snap$lookback),
					info = paste0(name, ": lookback attribute")
				)
			}
		})
	}

	invisible(NULL)
}

.parity_run()
