## tests/testthat/test-parity.R
##
## AUTO-GENERATED. Do not edit this file in tests/testthat/ - edit the
## source template at codegen/parity/test_parity_template.R instead.
## The Makefile copies this template into tests/testthat/test-parity.R
## before running `make test` / `make check` / `make parity`, and
## removes it again on `make clean` / `make purge`.
##
## What this checks:
##   For every .rds in $TALIB_PARITY_SNAPSHOT_DIR, resolve the matching
##   R wrapper via the package's alias convention (every TA-Lib name X
##   is exported as both x_long_name() and X()), invoke it, and compare
##   each output column positionally against the snapshot using
##   all.equal() with sqrt(.Machine$double.eps) tolerance.
##
## Skip behaviour:
##   -  ensures CRAN's automated checks see SKIP, not RUN.
##   - skip when TALIB_PARITY_SNAPSHOT_DIR is unset or empty (e.g. when
##     someone runs devtools::test() without first running `make parity`).

suppressPackageStartupMessages(library(talib))

## Force candlestick wrappers to emit raw -100/0/100 ints (the form
## upstream produces). Without this they divide by 100 and would never
## match the snapshot.
options(talib.normalize = FALSE)

.parity_snapshot_dir <- function() {
	d <- Sys.getenv("TALIB_PARITY_SNAPSHOT_DIR", unset = "")
	if (!nzchar(d)) {
		return(NULL)
	}
	if (!dir.exists(d)) {
		return(NULL)
	}
	d
}

## ---- Per-indicator R-call overrides -------------------------------------
##
## Default invocation: do.call(name, list(BTC)) - one positional data.frame
## arg. A handful of wrappers take separate (x, y, ...) args; encode those
## here. NOT a spec catalog - call shape only, no parameter values.

R_CALL_OVERRIDES <- list(
	## Vector-input wrappers (rolling_*, etc).
	CORREL = function(btc, snap) {
		talib::CORREL(btc$high, btc$low, n = snap_n(snap))
	},
	BETA = function(btc, snap) talib::BETA(btc$high, btc$low, n = snap_n(snap)),
	VAR = function(btc, snap) talib::VAR(btc$close, n = snap_n(snap)),
	STDDEV = function(btc, snap) talib::STDDEV(btc$close, n = snap_n(snap)),
	MAX = function(btc, snap) talib::MAX(btc$close, n = snap_n(snap)),
	MIN = function(btc, snap) talib::MIN(btc$close, n = snap_n(snap)),
	SUM = function(btc, snap) talib::SUM(btc$close, n = snap_n(snap)),
	## MAMA: the R wrapper routes through TA_MA(maType=MAMA), which
	## internally calls TA_MAMA(close, 0.5, 0.05) and discards the FAMA
	## output. So the wrapper returns 1 column; upstream TA_MAMA returns 2
	## (outMAMA, outFAMA). The MAMA column itself is bit-identical, so
	## we compare just that column. The missing FAMA column is tracked as
	## an intentional wrapper asymmetry (see repo issue tracker).
	MAMA = list(
		call = function(btc, snap) talib::MAMA(btc),
		compare_cols = 1L
	),
	## STOCHRSI: the R wrapper exposes two periods (n_rsi for the inner
	## TA_RSI call, n for the outer TA_STOCHRSI step). The snapshot for
	## STOCHRSI is generated as a composite (TA_RSI -> strip -> TA_STOCHRSI)
	## in parity_gen.c, matching the wrapper exactly. No override needed
	## beyond calling the wrapper with no args.
	STOCHRSI = function(btc, snap) talib::STOCHRSI(btc),
	## MACDEXT: R wrapper takes MA-spec lists (fast = EMA(n=12), etc.);
	## TA-Lib upstream defaults all three MAType to SMA. Mirror upstream
	## defaults explicitly so we test the same configuration.
	MACDEXT = function(btc, snap) {
		opts <- snap$opt_inputs
		talib::MACDEXT(
			btc,
			fast = talib::SMA(n = as.integer(opts$optInFastPeriod)),
			slow = talib::SMA(n = as.integer(opts$optInSlowPeriod)),
			signal = talib::SMA(n = as.integer(opts$optInSignalPeriod))
		)
	}
)

snap_n <- function(snap, default = 30L) {
	v <- snap$opt_inputs$optInTimePeriod
	if (is.null(v) || !nzchar(v)) {
		return(default)
	}
	as.integer(v)
}

## Generic TA-Lib opt -> R wrapper arg translation. Many R wrappers
## default to a different `n` than TA-Lib (e.g. SMA's R default is 10,
## TA-Lib's metadata default is 30). Forwarding the snapshot's
## optInTimePeriod into the wrapper as `n` keeps the test apples-to-apples.
TA_TO_R_ARG <- c(
	optInTimePeriod = "n",
	optInFastPeriod = "fast",
	optInSlowPeriod = "slow",
	optInSignalPeriod = "signal"
)

coerce_opt <- function(ta_name, value) {
	if (grepl("Period", ta_name, fixed = TRUE)) {
		return(as.integer(value))
	}
	if (grepl("MAType", ta_name, fixed = TRUE)) {
		return(as.integer(value))
	}
	suppressWarnings(as.numeric(value))
}

build_args_from_snap <- function(snap) {
	opts <- snap$opt_inputs
	args <- list()
	for (ta_name in names(opts)) {
		r_name <- TA_TO_R_ARG[ta_name]
		if (is.na(r_name)) {
			next
		}
		args[[r_name]] <- coerce_opt(ta_name, opts[[ta_name]])
	}
	args
}

## Invoke the R wrapper for an indicator. Returns a list:
##   result       - the raw output (matrix / data.frame / NULL)
##   compare_cols - NULL to compare all columns (default), or an integer
##                  N to restrict comparison to the first N columns
##                  (used when the wrapper intentionally exposes a subset
##                  of upstream's output slots; e.g. MAMA drops FAMA)
call_r_wrapper <- function(name, btc, snap) {
	override <- R_CALL_OVERRIDES[[name]]
	if (identical(override, NA)) {
		return(list(result = NULL, compare_cols = NULL))
	}
	if (is.function(override)) {
		return(list(result = override(btc, snap), compare_cols = NULL))
	}
	if (is.list(override)) {
		return(list(
			result = override$call(btc, snap),
			compare_cols = override$compare_cols
		))
	}
	fn <- get(name, envir = asNamespace("talib"), inherits = FALSE)
	args <- build_args_from_snap(snap)
	list(result = do.call(fn, c(list(btc), args)), compare_cols = NULL)
}

## ---- Test enumeration ---------------------------------------------------
##
## We emit one test_that() per indicator so the testthat report shows
## per-indicator PASS/FAIL/SKIP. Each test calls  before
## doing any real work; if the snapshot dir is unavailable we skip the
## entire batch with a single sentinel test that explains why.

.parity_run <- function() {
	snapshot_dir <- .parity_snapshot_dir()
	if (is.null(snapshot_dir)) {
		test_that("parity: TA-Lib upstream snapshot present", {
			skip(paste0(
				"TALIB_PARITY_SNAPSHOT_DIR is unset or missing.\n",
				"Run `make parity` to generate the snapshot."
			))
		})
		return(invisible(NULL))
	}

	snap_files <- list.files(
		snapshot_dir,
		pattern = "\\.rds$",
		full.names = TRUE
	)
	if (length(snap_files) == 0L) {
		test_that("parity: TA-Lib upstream snapshot present", {
			skip(paste0("No .rds files in ", snapshot_dir))
		})
		return(invisible(NULL))
	}

	tol <- sqrt(.Machine$double.eps)

	for (snap_file in snap_files) {
		snap <- readRDS(snap_file)
		name <- snap$upstream

		test_that(paste0("parity: ", name), {
			expect_true(
				exists(name, envir = asNamespace("talib"), inherits = FALSE),
				info = paste0(
					"R wrapper '",
					name,
					"' must be exported by talib"
				)
			)

			called <- call_r_wrapper(name, BTC, snap)
			result <- called$result
			if (is.null(result)) {
				skip(paste0(
					name,
					": R wrapper diverges from upstream entry point"
				))
			}

			mat <- if (is.matrix(result)) {
				result
			} else if (is.data.frame(result)) {
				as.matrix(result)
			} else if (is.numeric(result)) {
				matrix(result, ncol = 1L)
			} else {
				fail(paste0(
					"unexpected result class for ",
					name,
					": ",
					paste(class(result), collapse = "/")
				))
				return(invisible(NULL))
			}

			## How many columns to compare. Default: all of upstream's.
			## Override: the wrapper intentionally exposes a subset
			## (e.g. MAMA returns 1 column vs upstream's 2).
			n_expected <- if (is.null(called$compare_cols)) {
				length(snap$output_names)
			} else {
				as.integer(called$compare_cols)
			}

			expect_equal(
				nrow(mat),
				nrow(BTC),
				info = paste0(name, ": row count mismatch")
			)
			expect_equal(
				ncol(mat),
				n_expected,
				info = paste0(
					name,
					": R column count (",
					ncol(mat),
					") does not match expected (",
					n_expected,
					")"
				)
			)

			for (i in seq_len(n_expected)) {
				r_col <- as.double(mat[, i])
				ta_col <- as.double(snap$outputs[[i]])
				expect_equal(
					r_col,
					ta_col,
					tolerance = tol,
					info = paste0(
						name,
						" col ",
						i,
						" (",
						snap$output_names[i],
						")"
					)
				)
			}

			lb <- attr(result, "lookback")
			if (
				!is.null(lb) && !is.null(snap$lookback) && !is.na(snap$lookback)
			) {
				expect_equal(
					as.integer(lb),
					as.integer(snap$lookback),
					info = paste0(name, ": lookback attribute")
				)
			}
		})
	}

	invisible(NULL)
}

.parity_run()
